# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BDotEstimate.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='BDotEstimate.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x12\x42\x44otEstimate.proto\"T\n\x0c\x42\x44otEstimate\x12\t\n\x01x\x18\x01 \x02(\x01\x12\t\n\x01y\x18\x02 \x02(\x01\x12\t\n\x01z\x18\x03 \x02(\x01\x12#\n\x1btimestamp_millis_unix_epoch\x18\x04 \x02(\x06')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BDOTESTIMATE = _descriptor.Descriptor(
  name='BDotEstimate',
  full_name='BDotEstimate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='BDotEstimate.x', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='BDotEstimate.y', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z', full_name='BDotEstimate.z', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp_millis_unix_epoch', full_name='BDotEstimate.timestamp_millis_unix_epoch', index=3,
      number=4, type=6, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=106,
)

DESCRIPTOR.message_types_by_name['BDotEstimate'] = _BDOTESTIMATE

BDotEstimate = _reflection.GeneratedProtocolMessageType('BDotEstimate', (_message.Message,), dict(
  DESCRIPTOR = _BDOTESTIMATE,
  __module__ = 'BDotEstimate_pb2'
  # @@protoc_insertion_point(class_scope:BDotEstimate)
  ))
_sym_db.RegisterMessage(BDotEstimate)


# @@protoc_insertion_point(module_scope)
