# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: InfraredReading.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='InfraredReading.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x15InfraredReading.proto\"C\n\x0fInfraredReading\x12\x17\n\x08infrared\x18\x01 \x02(\x02:\x05-9999\x12\x17\n\x0ctimestamp_ms\x18\x02 \x02(\x06:\x01\x30')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_INFRAREDREADING = _descriptor.Descriptor(
  name='InfraredReading',
  full_name='InfraredReading',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='infrared', full_name='InfraredReading.infrared', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(-9999),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp_ms', full_name='InfraredReading.timestamp_ms', index=1,
      number=2, type=6, cpp_type=4, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=92,
)

DESCRIPTOR.message_types_by_name['InfraredReading'] = _INFRAREDREADING

InfraredReading = _reflection.GeneratedProtocolMessageType('InfraredReading', (_message.Message,), dict(
  DESCRIPTOR = _INFRAREDREADING,
  __module__ = 'InfraredReading_pb2'
  # @@protoc_insertion_point(class_scope:InfraredReading)
  ))
_sym_db.RegisterMessage(InfraredReading)


# @@protoc_insertion_point(module_scope)
