message_codes = {
    "magnetometer_reading_request_code": 0x06,
    "bms1_input_current_reading_code": 0x01,
    "bms1_input_voltage_reading_code": 0x02,
    "primary_mcu_regulator_current_reading_code": 0x03,
    "magnetorquer_x_current_reading_code": 0x04,
    "adcs_system_state_reading_code": 0x05,
    "torque_output_reading_code": 0x07,
    "magnetometer_reading_code": 0x08,
    "test_sensor_reading_code": 0x09,
    "test_sensor_reading_linked_request_code": 0x0A,
    "test_sensor_reading_request_code": 0x0B,
    "tle_request_code": 0x0C,
    "location_reading_code": 0x0D,
    "gyrometer_reading_request_code": 0x0E,
    "calibrated_magnetometer_reading_code": 0x0F,
}
