# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SensorReading.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SensorReading.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x13SensorReading.proto\">\n\rSensorReading\x12\x14\n\x05value\x18\x01 \x02(\x01:\x05-9999\x12\x17\n\x0ctimestamp_ms\x18\x02 \x02(\x06:\x01\x30')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SENSORREADING = _descriptor.Descriptor(
  name='SensorReading',
  full_name='SensorReading',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='SensorReading.value', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=True, default_value=float(-9999),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp_ms', full_name='SensorReading.timestamp_ms', index=1,
      number=2, type=6, cpp_type=4, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=85,
)

DESCRIPTOR.message_types_by_name['SensorReading'] = _SENSORREADING

SensorReading = _reflection.GeneratedProtocolMessageType('SensorReading', (_message.Message,), dict(
  DESCRIPTOR = _SENSORREADING,
  __module__ = 'SensorReading_pb2'
  # @@protoc_insertion_point(class_scope:SensorReading)
  ))
_sym_db.RegisterMessage(SensorReading)


# @@protoc_insertion_point(module_scope)
