# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StateMachineStateReading.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='StateMachineStateReading.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x1eStateMachineStateReading.proto\"N\n\x18StateMachineStateReading\x12\r\n\x05state\x18\x01 \x02(\x05\x12#\n\x1btimestamp_millis_unix_epoch\x18\x02 \x02(\x06')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_STATEMACHINESTATEREADING = _descriptor.Descriptor(
  name='StateMachineStateReading',
  full_name='StateMachineStateReading',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='StateMachineStateReading.state', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp_millis_unix_epoch', full_name='StateMachineStateReading.timestamp_millis_unix_epoch', index=1,
      number=2, type=6, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=112,
)

DESCRIPTOR.message_types_by_name['StateMachineStateReading'] = _STATEMACHINESTATEREADING

StateMachineStateReading = _reflection.GeneratedProtocolMessageType('StateMachineStateReading', (_message.Message,), dict(
  DESCRIPTOR = _STATEMACHINESTATEREADING,
  __module__ = 'StateMachineStateReading_pb2'
  # @@protoc_insertion_point(class_scope:StateMachineStateReading)
  ))
_sym_db.RegisterMessage(StateMachineStateReading)


# @@protoc_insertion_point(module_scope)
