# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TorqueOutputReading.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='TorqueOutputReading.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x19TorqueOutputReading.proto\"[\n\x13TorqueOutputReading\x12\t\n\x01x\x18\x01 \x02(\x01\x12\t\n\x01y\x18\x02 \x02(\x01\x12\t\n\x01z\x18\x03 \x02(\x01\x12#\n\x1btimestamp_millis_unix_epoch\x18\x04 \x02(\x06')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TORQUEOUTPUTREADING = _descriptor.Descriptor(
  name='TorqueOutputReading',
  full_name='TorqueOutputReading',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='TorqueOutputReading.x', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='TorqueOutputReading.y', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z', full_name='TorqueOutputReading.z', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp_millis_unix_epoch', full_name='TorqueOutputReading.timestamp_millis_unix_epoch', index=3,
      number=4, type=6, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=120,
)

DESCRIPTOR.message_types_by_name['TorqueOutputReading'] = _TORQUEOUTPUTREADING

TorqueOutputReading = _reflection.GeneratedProtocolMessageType('TorqueOutputReading', (_message.Message,), dict(
  DESCRIPTOR = _TORQUEOUTPUTREADING,
  __module__ = 'TorqueOutputReading_pb2'
  # @@protoc_insertion_point(class_scope:TorqueOutputReading)
  ))
_sym_db.RegisterMessage(TorqueOutputReading)


# @@protoc_insertion_point(module_scope)
