#ifndef SRC_SENSORS_MEASURABLE_ID_H_
#define SRC_SENSORS_MEASURABLE_ID_H_

enum MeasurableId {
    kCommsAdc1,
    kCommsAdc2,
    kCommsAdc3,
    kCommsTemp1,
    kCommsTemp2,
    kPowerAdc1,
    kPowerAdc2,
    kPowerAdc3,
    kPowerTemp1,
    kPowerTemp2,
    kPowerBmsDieTemp1,
    kPowerBmsDieTemp2,
    kPowerBmsBatteryTemp1,
    kPowerBmsBatteryTemp2,
    kFsAdc1,
    kFsAdc2,
    kFsAdc3,
    kFsAdc4,
    kFsTempHbX,
    kFsTempHbY,
    kFsTempHbZ,
    kFsImuGyro1,
    kFsImuAccelerometer1,
    kFsImuTemperature1,
    kFsImuMagnetometer1,
    kFsImuGyro2,
    kFsImuAccelerometer2,
    kFsImuTemperature2,
    kFsImuMagnetometer2,
    kUtilAdc2,
    kUtilTemp1,
    kCdhAdc1,
    kCdhAdc2,
    kCdhSysTemp,
    kCdhRtc,
    kSolarAdc1,
    kSolarTemp1,
    kSolarTemp2,
    kMeasurableIdEnd
};

#endif  // SRC_SENSORS_MEASURABLE_ID_H_
