/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Tue Nov 27 21:57:23 2018. */

#include "AntennaBurnerInfoReading.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const uint64_t AntennaBurnerInfoReading_last_burn_attempt_timestamp_ms_default = 0ull;
const uint64_t AntennaBurnerInfoReading_burn_interval_ms_default = 0ull;
const bool AntennaBurnerInfoReading_attempt_antenna_burn_default = false;
const uint64_t AntennaBurnerInfoReading_timestamp_ms_default = 0ull;


const pb_field_t AntennaBurnerInfoReading_fields[5] = {
    PB_FIELD(  1, FIXED64 , REQUIRED, STATIC  , FIRST, AntennaBurnerInfoReading, last_burn_attempt_timestamp_ms, last_burn_attempt_timestamp_ms, &AntennaBurnerInfoReading_last_burn_attempt_timestamp_ms_default),
    PB_FIELD(  2, FIXED64 , REQUIRED, STATIC  , OTHER, AntennaBurnerInfoReading, burn_interval_ms, last_burn_attempt_timestamp_ms, &AntennaBurnerInfoReading_burn_interval_ms_default),
    PB_FIELD(  3, BOOL    , REQUIRED, STATIC  , OTHER, AntennaBurnerInfoReading, attempt_antenna_burn, burn_interval_ms, &AntennaBurnerInfoReading_attempt_antenna_burn_default),
    PB_FIELD(  7, FIXED64 , REQUIRED, STATIC  , OTHER, AntennaBurnerInfoReading, timestamp_ms, attempt_antenna_burn, &AntennaBurnerInfoReading_timestamp_ms_default),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
