/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.1 at Tue Nov 27 21:57:23 2018. */

#ifndef PB_ANTENNABURNERINFOREADING_PB_H_INCLUDED
#define PB_ANTENNABURNERINFOREADING_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _AntennaBurnerInfoReading {
    uint64_t last_burn_attempt_timestamp_ms;
    uint64_t burn_interval_ms;
    bool attempt_antenna_burn;
    uint64_t timestamp_ms;
/* @@protoc_insertion_point(struct:AntennaBurnerInfoReading) */
} AntennaBurnerInfoReading;

/* Default values for struct fields */
extern const uint64_t AntennaBurnerInfoReading_last_burn_attempt_timestamp_ms_default;
extern const uint64_t AntennaBurnerInfoReading_burn_interval_ms_default;
extern const bool AntennaBurnerInfoReading_attempt_antenna_burn_default;
extern const uint64_t AntennaBurnerInfoReading_timestamp_ms_default;

/* Initializer values for message structs */
#define AntennaBurnerInfoReading_init_default    {0ull, 0ull, false, 0ull}
#define AntennaBurnerInfoReading_init_zero       {0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define AntennaBurnerInfoReading_last_burn_attempt_timestamp_ms_tag 1
#define AntennaBurnerInfoReading_burn_interval_ms_tag 2
#define AntennaBurnerInfoReading_attempt_antenna_burn_tag 3
#define AntennaBurnerInfoReading_timestamp_ms_tag 7

/* Struct field encoding specification for nanopb */
extern const pb_field_t AntennaBurnerInfoReading_fields[5];

/* Maximum encoded size of messages (where known) */
#define AntennaBurnerInfoReading_size            29

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define ANTENNABURNERINFOREADING_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
