/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Wed Sep 26 22:08:12 2018. */

#include "BmsChargingInfoReading.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const BmsChargingInfoReading_SystemStatus BmsChargingInfoReading_system_status_default = BmsChargingInfoReading_SystemStatus_kChargeDisable;
const BmsChargingInfoReading_ChargerState BmsChargingInfoReading_charger_state_default = BmsChargingInfoReading_ChargerState_kInvalidChargerState;
const BmsChargingInfoReading_ChargeStatus BmsChargingInfoReading_charge_status_default = BmsChargingInfoReading_ChargeStatus_kChargingError;
const uint32_t BmsChargingInfoReading_q_count_default = 9999u;
const int32_t BmsChargingInfoReading_q_count_delta_default = -9999;
const bool BmsChargingInfoReading_first_charge_complete_default = false;
const uint64_t BmsChargingInfoReading_timestamp_ms_default = 0ull;


const pb_field_t BmsChargingInfoReading_fields[8] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, BmsChargingInfoReading, system_status, system_status, &BmsChargingInfoReading_system_status_default),
    PB_FIELD(  2, UENUM   , REQUIRED, STATIC  , OTHER, BmsChargingInfoReading, charger_state, system_status, &BmsChargingInfoReading_charger_state_default),
    PB_FIELD(  3, UENUM   , REQUIRED, STATIC  , OTHER, BmsChargingInfoReading, charge_status, charger_state, &BmsChargingInfoReading_charge_status_default),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, BmsChargingInfoReading, q_count, charge_status, &BmsChargingInfoReading_q_count_default),
    PB_FIELD(  5, INT32   , REQUIRED, STATIC  , OTHER, BmsChargingInfoReading, q_count_delta, q_count, &BmsChargingInfoReading_q_count_delta_default),
    PB_FIELD(  6, BOOL    , REQUIRED, STATIC  , OTHER, BmsChargingInfoReading, first_charge_complete, q_count_delta, &BmsChargingInfoReading_first_charge_complete_default),
    PB_FIELD(  7, FIXED64 , REQUIRED, STATIC  , OTHER, BmsChargingInfoReading, timestamp_ms, first_charge_complete, &BmsChargingInfoReading_timestamp_ms_default),
    PB_LAST_FIELD
};





/* @@protoc_insertion_point(eof) */
