/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Wed Sep 26 21:59:31 2018. */

#include "BmsOperationValuesReading.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const double BmsOperationValuesReading_recharge_threshold_default = -9999;
const uint32_t BmsOperationValuesReading_c_over_x_threshold_default = 9999u;
const int32_t BmsOperationValuesReading_q_count_prescale_factor_default = -9999;
const uint64_t BmsOperationValuesReading_timestamp_ms_default = 0ull;


const pb_field_t BmsOperationValuesReading_fields[5] = {
    PB_FIELD(  1, DOUBLE  , REQUIRED, STATIC  , FIRST, BmsOperationValuesReading, recharge_threshold, recharge_threshold, &BmsOperationValuesReading_recharge_threshold_default),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, BmsOperationValuesReading, c_over_x_threshold, recharge_threshold, &BmsOperationValuesReading_c_over_x_threshold_default),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, BmsOperationValuesReading, q_count_prescale_factor, c_over_x_threshold, &BmsOperationValuesReading_q_count_prescale_factor_default),
    PB_FIELD(  4, FIXED64 , REQUIRED, STATIC  , OTHER, BmsOperationValuesReading, timestamp_ms, q_count_prescale_factor, &BmsOperationValuesReading_timestamp_ms_default),
    PB_LAST_FIELD
};


/* On some platforms (such as AVR), double is really float.
 * These are not directly supported by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

/* @@protoc_insertion_point(eof) */
