/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Fri Sep 07 16:58:18 2018. */

#include "BmsReadings.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const double BmsReadings_battery_voltage_default = -9999;
const double BmsReadings_battery_current_default = -9999;
const double BmsReadings_system_voltage_default = -9999;
const double BmsReadings_input_voltage_default = -9999;
const double BmsReadings_input_current_default = -9999;
const double BmsReadings_die_temperature_default = -9999;
const double BmsReadings_battery_temperature_default = -9999;
const uint32_t BmsReadings_jeita_region_default = 9999u;
const uint32_t BmsReadings_system_status_default = 9999u;
const uint32_t BmsReadings_charger_state_default = 9999u;
const uint32_t BmsReadings_charge_status_default = 9999u;
const double BmsReadings_recharge_threshold_default = -9999;
const uint32_t BmsReadings_charger_config_default = 9999u;
const uint32_t BmsReadings_c_over_x_threshold_default = 9999u;
const uint32_t BmsReadings_v_charge_setting_default = 9999u;
const uint32_t BmsReadings_i_charge_target_default = 9999u;
const uint32_t BmsReadings_config_bits_default = 9999u;
const uint32_t BmsReadings_q_count_default = 9999u;
const uint32_t BmsReadings_q_count_prescale_factor_default = 9999u;
const uint32_t BmsReadings_v_in_uvcl_setting_default = 9999u;
const double BmsReadings_v_charge_dac_default = -9999;
const double BmsReadings_i_charge_dac_default = -9999;
const bool BmsReadings_telemetry_valid_default = false;


const pb_field_t BmsReadings_fields[24] = {
    PB_FIELD(  1, DOUBLE  , REQUIRED, STATIC  , FIRST, BmsReadings, battery_voltage, battery_voltage, &BmsReadings_battery_voltage_default),
    PB_FIELD(  2, DOUBLE  , REQUIRED, STATIC  , OTHER, BmsReadings, battery_current, battery_voltage, &BmsReadings_battery_current_default),
    PB_FIELD(  3, DOUBLE  , REQUIRED, STATIC  , OTHER, BmsReadings, system_voltage, battery_current, &BmsReadings_system_voltage_default),
    PB_FIELD(  4, DOUBLE  , REQUIRED, STATIC  , OTHER, BmsReadings, input_voltage, system_voltage, &BmsReadings_input_voltage_default),
    PB_FIELD(  5, DOUBLE  , REQUIRED, STATIC  , OTHER, BmsReadings, input_current, input_voltage, &BmsReadings_input_current_default),
    PB_FIELD(  6, DOUBLE  , REQUIRED, STATIC  , OTHER, BmsReadings, die_temperature, input_current, &BmsReadings_die_temperature_default),
    PB_FIELD(  7, DOUBLE  , REQUIRED, STATIC  , OTHER, BmsReadings, battery_temperature, die_temperature, &BmsReadings_battery_temperature_default),
    PB_FIELD(  8, UINT32  , REQUIRED, STATIC  , OTHER, BmsReadings, jeita_region, battery_temperature, &BmsReadings_jeita_region_default),
    PB_FIELD(  9, UINT32  , REQUIRED, STATIC  , OTHER, BmsReadings, system_status, jeita_region, &BmsReadings_system_status_default),
    PB_FIELD( 10, UINT32  , REQUIRED, STATIC  , OTHER, BmsReadings, charger_state, system_status, &BmsReadings_charger_state_default),
    PB_FIELD( 11, UINT32  , REQUIRED, STATIC  , OTHER, BmsReadings, charge_status, charger_state, &BmsReadings_charge_status_default),
    PB_FIELD( 12, DOUBLE  , REQUIRED, STATIC  , OTHER, BmsReadings, recharge_threshold, charge_status, &BmsReadings_recharge_threshold_default),
    PB_FIELD( 13, UINT32  , REQUIRED, STATIC  , OTHER, BmsReadings, charger_config, recharge_threshold, &BmsReadings_charger_config_default),
    PB_FIELD( 14, UINT32  , REQUIRED, STATIC  , OTHER, BmsReadings, c_over_x_threshold, charger_config, &BmsReadings_c_over_x_threshold_default),
    PB_FIELD( 15, UINT32  , REQUIRED, STATIC  , OTHER, BmsReadings, v_charge_setting, c_over_x_threshold, &BmsReadings_v_charge_setting_default),
    PB_FIELD( 16, UINT32  , REQUIRED, STATIC  , OTHER, BmsReadings, i_charge_target, v_charge_setting, &BmsReadings_i_charge_target_default),
    PB_FIELD( 17, UINT32  , REQUIRED, STATIC  , OTHER, BmsReadings, config_bits, i_charge_target, &BmsReadings_config_bits_default),
    PB_FIELD( 18, UINT32  , REQUIRED, STATIC  , OTHER, BmsReadings, q_count, config_bits, &BmsReadings_q_count_default),
    PB_FIELD( 19, UINT32  , REQUIRED, STATIC  , OTHER, BmsReadings, q_count_prescale_factor, q_count, &BmsReadings_q_count_prescale_factor_default),
    PB_FIELD( 20, UINT32  , REQUIRED, STATIC  , OTHER, BmsReadings, v_in_uvcl_setting, q_count_prescale_factor, &BmsReadings_v_in_uvcl_setting_default),
    PB_FIELD( 21, DOUBLE  , REQUIRED, STATIC  , OTHER, BmsReadings, v_charge_dac, v_in_uvcl_setting, &BmsReadings_v_charge_dac_default),
    PB_FIELD( 22, DOUBLE  , REQUIRED, STATIC  , OTHER, BmsReadings, i_charge_dac, v_charge_dac, &BmsReadings_i_charge_dac_default),
    PB_FIELD( 23, BOOL    , REQUIRED, STATIC  , OTHER, BmsReadings, telemetry_valid, i_charge_dac, &BmsReadings_telemetry_valid_default),
    PB_LAST_FIELD
};


/* On some platforms (such as AVR), double is really float.
 * These are not directly supported by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

/* @@protoc_insertion_point(eof) */
