/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.1 at Wed Sep 26 21:59:31 2018. */

#ifndef PB_BMSSETTINGSREADING_PB_H_INCLUDED
#define PB_BMSSETTINGSREADING_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _BmsSettingsReading {
    uint32_t charger_config;
    uint32_t v_charge_setting;
    uint32_t i_charge_target;
    uint32_t config_bits;
    uint32_t v_in_uvcl_setting;
    bool telemetry_valid;
    uint64_t timestamp_ms;
/* @@protoc_insertion_point(struct:BmsSettingsReading) */
} BmsSettingsReading;

/* Default values for struct fields */
extern const uint32_t BmsSettingsReading_charger_config_default;
extern const uint32_t BmsSettingsReading_v_charge_setting_default;
extern const uint32_t BmsSettingsReading_i_charge_target_default;
extern const uint32_t BmsSettingsReading_config_bits_default;
extern const uint32_t BmsSettingsReading_v_in_uvcl_setting_default;
extern const bool BmsSettingsReading_telemetry_valid_default;
extern const uint64_t BmsSettingsReading_timestamp_ms_default;

/* Initializer values for message structs */
#define BmsSettingsReading_init_default          {9999u, 9999u, 9999u, 9999u, 9999u, false, 0ull}
#define BmsSettingsReading_init_zero             {0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define BmsSettingsReading_charger_config_tag    1
#define BmsSettingsReading_v_charge_setting_tag  2
#define BmsSettingsReading_i_charge_target_tag   3
#define BmsSettingsReading_config_bits_tag       4
#define BmsSettingsReading_v_in_uvcl_setting_tag 5
#define BmsSettingsReading_telemetry_valid_tag   6
#define BmsSettingsReading_timestamp_ms_tag      7

/* Struct field encoding specification for nanopb */
extern const pb_field_t BmsSettingsReading_fields[8];

/* Maximum encoded size of messages (where known) */
#define BmsSettingsReading_size                  41

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define BMSSETTINGSREADING_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
