/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Wed Sep 26 02:18:07 2018. */

#include "BmsTemperatureReading.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const double BmsTemperatureReading_die_temperature_default = -9999;
const double BmsTemperatureReading_battery_temperature_default = -9999;
const uint32_t BmsTemperatureReading_jeita_region_default = 9999u;
const uint64_t BmsTemperatureReading_timestamp_ms_default = 0ull;


const pb_field_t BmsTemperatureReading_fields[5] = {
    PB_FIELD(  1, DOUBLE  , REQUIRED, STATIC  , FIRST, BmsTemperatureReading, die_temperature, die_temperature, &BmsTemperatureReading_die_temperature_default),
    PB_FIELD(  2, DOUBLE  , REQUIRED, STATIC  , OTHER, BmsTemperatureReading, battery_temperature, die_temperature, &BmsTemperatureReading_battery_temperature_default),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, BmsTemperatureReading, jeita_region, battery_temperature, &BmsTemperatureReading_jeita_region_default),
    PB_FIELD(  4, FIXED64 , REQUIRED, STATIC  , OTHER, BmsTemperatureReading, timestamp_ms, jeita_region, &BmsTemperatureReading_timestamp_ms_default),
    PB_LAST_FIELD
};


/* On some platforms (such as AVR), double is really float.
 * These are not directly supported by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

/* @@protoc_insertion_point(eof) */
