/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Wed Sep 26 22:30:44 2018. */

#include "BmsVoltagesReading.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const double BmsVoltagesReading_battery_voltage_default = -9999;
const double BmsVoltagesReading_system_voltage_default = -9999;
const double BmsVoltagesReading_input_voltage_default = -9999;
const uint64_t BmsVoltagesReading_timestamp_ms_default = 0ull;


const pb_field_t BmsVoltagesReading_fields[5] = {
    PB_FIELD(  1, DOUBLE  , REQUIRED, STATIC  , FIRST, BmsVoltagesReading, battery_voltage, battery_voltage, &BmsVoltagesReading_battery_voltage_default),
    PB_FIELD(  2, DOUBLE  , REQUIRED, STATIC  , OTHER, BmsVoltagesReading, system_voltage, battery_voltage, &BmsVoltagesReading_system_voltage_default),
    PB_FIELD(  3, DOUBLE  , REQUIRED, STATIC  , OTHER, BmsVoltagesReading, input_voltage, system_voltage, &BmsVoltagesReading_input_voltage_default),
    PB_FIELD(  4, FIXED64 , REQUIRED, STATIC  , OTHER, BmsVoltagesReading, timestamp_ms, input_voltage, &BmsVoltagesReading_timestamp_ms_default),
    PB_LAST_FIELD
};


/* On some platforms (such as AVR), double is really float.
 * These are not directly supported by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

/* @@protoc_insertion_point(eof) */
