/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Sun Sep 09 00:21:21 2018. */

#include "ConsoleMessage.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ConsoleMessage_fields[2] = {
    PB_FIELD(  1, BYTES   , REQUIRED, STATIC  , FIRST, ConsoleMessage, message, message, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
