/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.1 at Sun Sep 09 00:21:21 2018. */

#ifndef PB_CONSOLEMESSAGE_PB_H_INCLUDED
#define PB_CONSOLEMESSAGE_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(100) ConsoleMessage_message_t;
typedef struct _ConsoleMessage {
    ConsoleMessage_message_t message;
/* @@protoc_insertion_point(struct:ConsoleMessage) */
} ConsoleMessage;

/* Default values for struct fields */

/* Initializer values for message structs */
#define ConsoleMessage_init_default              {{0, {0}}}
#define ConsoleMessage_init_zero                 {{0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define ConsoleMessage_message_tag               1

/* Struct field encoding specification for nanopb */
extern const pb_field_t ConsoleMessage_fields[2];

/* Maximum encoded size of messages (where known) */
#define ConsoleMessage_size                      102

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define CONSOLEMESSAGE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
