/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Tue Jul 31 18:56:38 2018. */

#include "CurrentReading.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t CurrentReading_fields[3] = {
    PB_FIELD(  1, FLOAT   , REQUIRED, STATIC  , FIRST, CurrentReading, current, current, 0),
    PB_FIELD(  2, FIXED64 , REQUIRED, STATIC  , OTHER, CurrentReading, timestamp_millis_unix_epoch, current, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
