/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Wed Sep 05 15:59:15 2018. */

#include "DeployAntennaCommandPayload.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t DeployAntennaCommandPayload_fields[2] = {
    PB_FIELD(  1, FIXED32 , REQUIRED, STATIC  , FIRST, DeployAntennaCommandPayload, deploy_antenna, deploy_antenna, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
