/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.1 at Sat Sep 22 20:28:34 2018. */

#ifndef PB_DEPLOYANTENNACOMMANDPAYLOAD_PB_H_INCLUDED
#define PB_DEPLOYANTENNACOMMANDPAYLOAD_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _DeployAntennaCommandPayload {
    uint32_t deploy_antenna;
/* @@protoc_insertion_point(struct:DeployAntennaCommandPayload) */
} DeployAntennaCommandPayload;

/* Default values for struct fields */
extern const uint32_t DeployAntennaCommandPayload_deploy_antenna_default;

/* Initializer values for message structs */
#define DeployAntennaCommandPayload_init_default {0u}
#define DeployAntennaCommandPayload_init_zero    {0}

/* Field tags (for use in manual encoding/decoding) */
#define DeployAntennaCommandPayload_deploy_antenna_tag 1

/* Struct field encoding specification for nanopb */
extern const pb_field_t DeployAntennaCommandPayload_fields[2];

/* Maximum encoded size of messages (where known) */
#define DeployAntennaCommandPayload_size         5

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define DEPLOYANTENNACOMMANDPAYLOAD_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
