/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Tue Oct 30 15:35:51 2018. */

#include "DeployAntennaUplinkPayload.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const uint32_t DeployAntennaUplinkPayload_deploy_antenna_default = 0u;


const pb_field_t DeployAntennaUplinkPayload_fields[2] = {
    PB_FIELD(  1, FIXED32 , REQUIRED, STATIC  , FIRST, DeployAntennaUplinkPayload, deploy_antenna, deploy_antenna, &DeployAntennaUplinkPayload_deploy_antenna_default),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
