/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Tue Oct 30 15:35:55 2018. */

#include "EnableDataloggerUplinkPayload.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const bool EnableDataloggerUplinkPayload_datalogger_enabled_default = true;


const pb_field_t EnableDataloggerUplinkPayload_fields[2] = {
    PB_FIELD(  1, BOOL    , REQUIRED, STATIC  , FIRST, EnableDataloggerUplinkPayload, datalogger_enabled, datalogger_enabled, &EnableDataloggerUplinkPayload_datalogger_enabled_default),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
