/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Wed Sep 05 19:32:47 2018. */

#include "EnableDataloggerCommandPayload.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t EnableDataloggerCommandPayload_fields[2] = {
    PB_FIELD(  1, BOOL    , REQUIRED, STATIC  , FIRST, EnableDataloggerCommandPayload, datalogger_enabled, datalogger_enabled, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
