/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Tue Nov 13 14:53:17 2018. */

#include "EraseFlashUplinkPayload.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const uint32_t EraseFlashUplinkPayload_erase_flash_default = 0u;


const pb_field_t EraseFlashUplinkPayload_fields[2] = {
    PB_FIELD(  1, FIXED32 , REQUIRED, STATIC  , FIRST, EraseFlashUplinkPayload, erase_flash, erase_flash, &EraseFlashUplinkPayload_erase_flash_default),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
