/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.1 at Tue Nov 13 14:53:17 2018. */

#ifndef PB_ERASEFLASHUPLINKPAYLOAD_PB_H_INCLUDED
#define PB_ERASEFLASHUPLINKPAYLOAD_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _EraseFlashUplinkPayload {
    uint32_t erase_flash;
/* @@protoc_insertion_point(struct:EraseFlashUplinkPayload) */
} EraseFlashUplinkPayload;

/* Default values for struct fields */
extern const uint32_t EraseFlashUplinkPayload_erase_flash_default;

/* Initializer values for message structs */
#define EraseFlashUplinkPayload_init_default     {0u}
#define EraseFlashUplinkPayload_init_zero        {0}

/* Field tags (for use in manual encoding/decoding) */
#define EraseFlashUplinkPayload_erase_flash_tag  1

/* Struct field encoding specification for nanopb */
extern const pb_field_t EraseFlashUplinkPayload_fields[2];

/* Maximum encoded size of messages (where known) */
#define EraseFlashUplinkPayload_size             5

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define ERASEFLASHUPLINKPAYLOAD_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
