/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.1 at Wed Oct 31 16:22:21 2018. */

#ifndef PB_EXECUTESECTIONSUPLINKPAYLOAD_PB_H_INCLUDED
#define PB_EXECUTESECTIONSUPLINKPAYLOAD_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _ExecuteSectionsUplinkPayload {
    bool post_buffer;
/* @@protoc_insertion_point(struct:ExecuteSectionsUplinkPayload) */
} ExecuteSectionsUplinkPayload;

/* Default values for struct fields */
extern const bool ExecuteSectionsUplinkPayload_post_buffer_default;

/* Initializer values for message structs */
#define ExecuteSectionsUplinkPayload_init_default {false}
#define ExecuteSectionsUplinkPayload_init_zero   {0}

/* Field tags (for use in manual encoding/decoding) */
#define ExecuteSectionsUplinkPayload_post_buffer_tag 1

/* Struct field encoding specification for nanopb */
extern const pb_field_t ExecuteSectionsUplinkPayload_fields[2];

/* Maximum encoded size of messages (where known) */
#define ExecuteSectionsUplinkPayload_size        2

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define EXECUTESECTIONSUPLINKPAYLOAD_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
