/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Wed Oct 31 16:22:21 2018. */

#include "ExecuteSectionsUplinkPayload.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const bool ExecuteSectionsUplinkPayload_post_buffer_default = false;


const pb_field_t ExecuteSectionsUplinkPayload_fields[2] = {
    PB_FIELD(  1, BOOL    , REQUIRED, STATIC  , FIRST, ExecuteSectionsUplinkPayload, post_buffer, post_buffer, &ExecuteSectionsUplinkPayload_post_buffer_default),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
