/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.1 at Tue Oct 30 15:36:07 2018. */

#ifndef PB_FORMATSDUPLINKPAYLOAD_PB_H_INCLUDED
#define PB_FORMATSDUPLINKPAYLOAD_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _FormatSdUplinkPayload {
    uint32_t sd_index;
/* @@protoc_insertion_point(struct:FormatSdUplinkPayload) */
} FormatSdUplinkPayload;

/* Default values for struct fields */
extern const uint32_t FormatSdUplinkPayload_sd_index_default;

/* Initializer values for message structs */
#define FormatSdUplinkPayload_init_default       {0u}
#define FormatSdUplinkPayload_init_zero          {0}

/* Field tags (for use in manual encoding/decoding) */
#define FormatSdUplinkPayload_sd_index_tag       1

/* Struct field encoding specification for nanopb */
extern const pb_field_t FormatSdUplinkPayload_fields[2];

/* Maximum encoded size of messages (where known) */
#define FormatSdUplinkPayload_size               6

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define FORMATSDUPLINKPAYLOAD_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
