/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.1 at Sat Sep 22 20:28:34 2018. */

#ifndef PB_GYROSCOPEREADING_PB_H_INCLUDED
#define PB_GYROSCOPEREADING_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _GyroscopeReading {
    float x;
    float y;
    float z;
    uint64_t timestamp_ms;
/* @@protoc_insertion_point(struct:GyroscopeReading) */
} GyroscopeReading;

/* Default values for struct fields */
extern const float GyroscopeReading_x_default;
extern const float GyroscopeReading_y_default;
extern const float GyroscopeReading_z_default;
extern const uint64_t GyroscopeReading_timestamp_ms_default;

/* Initializer values for message structs */
#define GyroscopeReading_init_default            {-9999, -9999, -9999, 0ull}
#define GyroscopeReading_init_zero               {0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define GyroscopeReading_x_tag                   1
#define GyroscopeReading_y_tag                   2
#define GyroscopeReading_z_tag                   3
#define GyroscopeReading_timestamp_ms_tag        4

/* Struct field encoding specification for nanopb */
extern const pb_field_t GyroscopeReading_fields[5];

/* Maximum encoded size of messages (where known) */
#define GyroscopeReading_size                    24

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define GYROSCOPEREADING_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
