/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 at Sat Apr 14 02:42:36 2018. */

#ifndef PB_GYROMETERREADING_PB_H_INCLUDED
#define PB_GYROMETERREADING_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _GyrometerReading {
    double x;
    double y;
    double z;
    uint64_t timestamp_millis_unix_epoch;
/* @@protoc_insertion_point(struct:GyrometerReading) */
} GyrometerReading;

/* Default values for struct fields */

/* Initializer values for message structs */
#define GyrometerReading_init_default            {0, 0, 0, 0}
#define GyrometerReading_init_zero               {0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define GyrometerReading_x_tag                   1
#define GyrometerReading_y_tag                   2
#define GyrometerReading_z_tag                   3
#define GyrometerReading_timestamp_millis_unix_epoch_tag 4

/* Struct field encoding specification for nanopb */
extern const pb_field_t GyrometerReading_fields[5];

/* Maximum encoded size of messages (where known) */
#define GyrometerReading_size                    36

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define GYROMETERREADING_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
