/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 at Wed May  2 23:13:09 2018. */

#ifndef PB_INFRAREDREADING_PB_H_INCLUDED
#define PB_INFRAREDREADING_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _InfraredReading {
    float positive_x;
    float negative_x;
    float positive_y;
    float negative_y;
    float negative_z_a;
    float negative_z_b;
    uint64_t timestamp_millis_unix_epoch;
/* @@protoc_insertion_point(struct:InfraredReading) */
} InfraredReading;

/* Default values for struct fields */

/* Initializer values for message structs */
#define InfraredReading_init_default             {0, 0, 0, 0, 0, 0, 0}
#define InfraredReading_init_zero                {0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define InfraredReading_positive_x_tag           1
#define InfraredReading_negative_x_tag           2
#define InfraredReading_positive_y_tag           3
#define InfraredReading_negative_y_tag           4
#define InfraredReading_negative_z_a_tag         5
#define InfraredReading_negative_z_b_tag         6
#define InfraredReading_timestamp_millis_unix_epoch_tag 7

/* Struct field encoding specification for nanopb */
extern const pb_field_t InfraredReading_fields[8];

/* Maximum encoded size of messages (where known) */
#define InfraredReading_size                     39

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define INFRAREDREADING_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
