/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Sun Nov  4 13:24:18 2018. */

#include "InfraredReading.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const float InfraredReading_infrared_default = -9999;
const uint64_t InfraredReading_timestamp_ms_default = 0ull;


const pb_field_t InfraredReading_fields[3] = {
    PB_FIELD(  1, FLOAT   , REQUIRED, STATIC  , FIRST, InfraredReading, infrared, infrared, &InfraredReading_infrared_default),
    PB_FIELD(  2, FIXED64 , REQUIRED, STATIC  , OTHER, InfraredReading, timestamp_ms, infrared, &InfraredReading_timestamp_ms_default),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
