/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Wed May  2 23:13:09 2018. */

#include "InfraredReading.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t InfraredReading_fields[8] = {
    PB_FIELD(  1, FLOAT   , REQUIRED, STATIC  , FIRST, InfraredReading, positive_x, positive_x, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, InfraredReading, negative_x, positive_x, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, InfraredReading, positive_y, negative_x, 0),
    PB_FIELD(  4, FLOAT   , REQUIRED, STATIC  , OTHER, InfraredReading, negative_y, positive_y, 0),
    PB_FIELD(  5, FLOAT   , REQUIRED, STATIC  , OTHER, InfraredReading, negative_z_a, negative_y, 0),
    PB_FIELD(  6, FLOAT   , REQUIRED, STATIC  , OTHER, InfraredReading, negative_z_b, negative_z_a, 0),
    PB_FIELD(  7, FIXED64 , REQUIRED, STATIC  , OTHER, InfraredReading, timestamp_millis_unix_epoch, negative_z_b, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
