/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 at Sun Nov  4 13:24:18 2018. */

#ifndef PB_INFRAREDREADING_PB_H_INCLUDED
#define PB_INFRAREDREADING_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _InfraredReading {
    float infrared;
    uint64_t timestamp_ms;
/* @@protoc_insertion_point(struct:InfraredReading) */
} InfraredReading;

/* Default values for struct fields */
extern const float InfraredReading_infrared_default;
extern const uint64_t InfraredReading_timestamp_ms_default;

/* Initializer values for message structs */
#define InfraredReading_init_default             {-9999, 0ull}
#define InfraredReading_init_zero                {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define InfraredReading_infrared_tag             1
#define InfraredReading_timestamp_ms_tag         2

/* Struct field encoding specification for nanopb */
extern const pb_field_t InfraredReading_fields[3];

/* Maximum encoded size of messages (where known) */
#define InfraredReading_size                     14

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define INFRAREDREADING_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
