/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Tue Oct 30 15:36:11 2018. */

#include "IoExpanderToggleUplinkPayload.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const uint32_t IoExpanderToggleUplinkPayload_io_expander_id_default = 0u;
const uint32_t IoExpanderToggleUplinkPayload_pin_default = 0u;
const uint32_t IoExpanderToggleUplinkPayload_toggle_type_default = 0u;
const uint32_t IoExpanderToggleUplinkPayload_toggle_duration_default = 0u;


const pb_field_t IoExpanderToggleUplinkPayload_fields[5] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, IoExpanderToggleUplinkPayload, io_expander_id, io_expander_id, &IoExpanderToggleUplinkPayload_io_expander_id_default),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, IoExpanderToggleUplinkPayload, pin, io_expander_id, &IoExpanderToggleUplinkPayload_pin_default),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, IoExpanderToggleUplinkPayload, toggle_type, pin, &IoExpanderToggleUplinkPayload_toggle_type_default),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, IoExpanderToggleUplinkPayload, toggle_duration, toggle_type, &IoExpanderToggleUplinkPayload_toggle_duration_default),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
