/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Fri Oct 19 22:06:41 2018. */

#include "IoExpanderToggleCommandPayload.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const uint32_t IoExpanderToggleCommandPayload_io_expander_id_default = 0u;
const uint32_t IoExpanderToggleCommandPayload_pin_default = 0u;
const uint32_t IoExpanderToggleCommandPayload_toggle_type_default = 0u;
const uint32_t IoExpanderToggleCommandPayload_toggle_duration_default = 0u;


const pb_field_t IoExpanderToggleCommandPayload_fields[5] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, IoExpanderToggleCommandPayload, io_expander_id, io_expander_id, &IoExpanderToggleCommandPayload_io_expander_id_default),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, IoExpanderToggleCommandPayload, pin, io_expander_id, &IoExpanderToggleCommandPayload_pin_default),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, IoExpanderToggleCommandPayload, toggle_type, pin, &IoExpanderToggleCommandPayload_toggle_type_default),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, IoExpanderToggleCommandPayload, toggle_duration, toggle_type, &IoExpanderToggleCommandPayload_toggle_duration_default),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
