/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Tue Oct 30 15:36:24 2018. */

#include "LithiumFastPaUplinkPayload.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const uint32_t LithiumFastPaUplinkPayload_pa_level_default = 0u;


const pb_field_t LithiumFastPaUplinkPayload_fields[2] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, LithiumFastPaUplinkPayload, pa_level, pa_level, &LithiumFastPaUplinkPayload_pa_level_default),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
