/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Mon Nov 19 14:03:29 2018. */

#include "LithiumConfigurationPayload.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const uint32_t LithiumConfigurationPayload_interface_baud_rate_8_default = 0u;
const uint32_t LithiumConfigurationPayload_tx_power_amp_level_8_default = 140u;
const uint32_t LithiumConfigurationPayload_rx_rf_baud_rate_8_default = 1u;
const uint32_t LithiumConfigurationPayload_tx_rf_baud_rate_8_default = 1u;
const uint32_t LithiumConfigurationPayload_rx_modulation_8_default = 0u;
const uint32_t LithiumConfigurationPayload_tx_modulation_8_default = 0u;
const uint32_t LithiumConfigurationPayload_rx_freq_32_default = 437200u;
const uint32_t LithiumConfigurationPayload_tx_freq_32_default = 437200u;
const pb_byte_t LithiumConfigurationPayload_source_default[6] = {0x41,0x43,0x52,0x55,0x58,0x31};
const pb_byte_t LithiumConfigurationPayload_destination_default[6] = {0x43,0x51,0x43,0x51,0x43,0x51};
const uint32_t LithiumConfigurationPayload_tx_preamble_16_default = 16u;
const uint32_t LithiumConfigurationPayload_tx_postamble_16_default = 0u;
const uint32_t LithiumConfigurationPayload_function_config_16_default = 28672u;
const uint32_t LithiumConfigurationPayload_function_config2_16_default = 1u;


const pb_field_t LithiumConfigurationPayload_fields[15] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, LithiumConfigurationPayload, interface_baud_rate_8, interface_baud_rate_8, &LithiumConfigurationPayload_interface_baud_rate_8_default),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, LithiumConfigurationPayload, tx_power_amp_level_8, interface_baud_rate_8, &LithiumConfigurationPayload_tx_power_amp_level_8_default),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, LithiumConfigurationPayload, rx_rf_baud_rate_8, tx_power_amp_level_8, &LithiumConfigurationPayload_rx_rf_baud_rate_8_default),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, LithiumConfigurationPayload, tx_rf_baud_rate_8, rx_rf_baud_rate_8, &LithiumConfigurationPayload_tx_rf_baud_rate_8_default),
    PB_FIELD(  5, UINT32  , REQUIRED, STATIC  , OTHER, LithiumConfigurationPayload, rx_modulation_8, tx_rf_baud_rate_8, &LithiumConfigurationPayload_rx_modulation_8_default),
    PB_FIELD(  6, UINT32  , REQUIRED, STATIC  , OTHER, LithiumConfigurationPayload, tx_modulation_8, rx_modulation_8, &LithiumConfigurationPayload_tx_modulation_8_default),
    PB_FIELD(  7, UINT32  , REQUIRED, STATIC  , OTHER, LithiumConfigurationPayload, rx_freq_32, tx_modulation_8, &LithiumConfigurationPayload_rx_freq_32_default),
    PB_FIELD(  8, UINT32  , REQUIRED, STATIC  , OTHER, LithiumConfigurationPayload, tx_freq_32, rx_freq_32, &LithiumConfigurationPayload_tx_freq_32_default),
    PB_FIELD( 10, FIXED_LENGTH_BYTES, REQUIRED, STATIC  , OTHER, LithiumConfigurationPayload, source, tx_freq_32, &LithiumConfigurationPayload_source_default),
    PB_FIELD( 11, FIXED_LENGTH_BYTES, REQUIRED, STATIC  , OTHER, LithiumConfigurationPayload, destination, source, &LithiumConfigurationPayload_destination_default),
    PB_FIELD( 12, UINT32  , REQUIRED, STATIC  , OTHER, LithiumConfigurationPayload, tx_preamble_16, destination, &LithiumConfigurationPayload_tx_preamble_16_default),
    PB_FIELD( 13, UINT32  , REQUIRED, STATIC  , OTHER, LithiumConfigurationPayload, tx_postamble_16, tx_preamble_16, &LithiumConfigurationPayload_tx_postamble_16_default),
    PB_FIELD( 14, UINT32  , REQUIRED, STATIC  , OTHER, LithiumConfigurationPayload, function_config_16, tx_postamble_16, &LithiumConfigurationPayload_function_config_16_default),
    PB_FIELD( 15, UINT32  , REQUIRED, STATIC  , OTHER, LithiumConfigurationPayload, function_config2_16, function_config_16, &LithiumConfigurationPayload_function_config2_16_default),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
