/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.1 at Sat Aug 11 11:05:50 2018. */

#ifndef PB_LITHIUMFASTPACOMMAND_PB_H_INCLUDED
#define PB_LITHIUMFASTPACOMMAND_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _LithiumFastPaCommand {
    uint32_t pa_level;
/* @@protoc_insertion_point(struct:LithiumFastPaCommand) */
} LithiumFastPaCommand;

/* Default values for struct fields */

/* Initializer values for message structs */
#define LithiumFastPaCommand_init_default        {0}
#define LithiumFastPaCommand_init_zero           {0}

/* Field tags (for use in manual encoding/decoding) */
#define LithiumFastPaCommand_pa_level_tag        1

/* Struct field encoding specification for nanopb */
extern const pb_field_t LithiumFastPaCommand_fields[2];

/* Maximum encoded size of messages (where known) */
#define LithiumFastPaCommand_size                5

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define LITHIUMFASTPACOMMAND_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
