/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Tue Oct 30 15:36:20 2018. */

#include "LithiumEnableUplinkPayload.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const bool LithiumEnableUplinkPayload_should_transmit_default = true;


const pb_field_t LithiumEnableUplinkPayload_fields[2] = {
    PB_FIELD(  1, BOOL    , REQUIRED, STATIC  , FIRST, LithiumEnableUplinkPayload, should_transmit, should_transmit, &LithiumEnableUplinkPayload_should_transmit_default),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
