/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.1 at Tue Nov 27 19:57:18 2018. */

#ifndef PB_LITHIUMTELEMETRYREADING_PB_H_INCLUDED
#define PB_LITHIUMTELEMETRYREADING_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(3) LithiumTelemetryReading_time_count_t;
typedef struct _LithiumTelemetryReading {
    uint32_t op_counter;
    uint32_t msp430_temp;
    LithiumTelemetryReading_time_count_t time_count;
    uint32_t rssi;
    uint32_t bytes_received;
    uint32_t bytes_transmitted;
    uint64_t timestamp_ms;
/* @@protoc_insertion_point(struct:LithiumTelemetryReading) */
} LithiumTelemetryReading;

/* Default values for struct fields */
extern const uint32_t LithiumTelemetryReading_op_counter_default;
extern const uint32_t LithiumTelemetryReading_msp430_temp_default;
extern const LithiumTelemetryReading_time_count_t LithiumTelemetryReading_time_count_default;
extern const uint32_t LithiumTelemetryReading_rssi_default;
extern const uint32_t LithiumTelemetryReading_bytes_received_default;
extern const uint32_t LithiumTelemetryReading_bytes_transmitted_default;
extern const uint64_t LithiumTelemetryReading_timestamp_ms_default;

/* Initializer values for message structs */
#define LithiumTelemetryReading_init_default     {0u, 0u, {0, {0}}, 0u, 0u, 0u, 0ull}
#define LithiumTelemetryReading_init_zero        {0, 0, {0, {0}}, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define LithiumTelemetryReading_op_counter_tag   1
#define LithiumTelemetryReading_msp430_temp_tag  2
#define LithiumTelemetryReading_time_count_tag   3
#define LithiumTelemetryReading_rssi_tag         4
#define LithiumTelemetryReading_bytes_received_tag 5
#define LithiumTelemetryReading_bytes_transmitted_tag 6
#define LithiumTelemetryReading_timestamp_ms_tag 7

/* Struct field encoding specification for nanopb */
extern const pb_field_t LithiumTelemetryReading_fields[8];

/* Maximum encoded size of messages (where known) */
#define LithiumTelemetryReading_size             39

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define LITHIUMTELEMETRYREADING_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
