/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.1 at Tue Oct 30 09:37:32 2018. */

#ifndef PB_LITHIUMMD5PAYLOAD_PB_H_INCLUDED
#define PB_LITHIUMMD5PAYLOAD_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _LithiumMd5Payload {
    pb_byte_t checksum[16];
/* @@protoc_insertion_point(struct:LithiumMd5Payload) */
} LithiumMd5Payload;

/* Default values for struct fields */

/* Initializer values for message structs */
#define LithiumMd5Payload_init_default           {{0}}
#define LithiumMd5Payload_init_zero              {{0}}

/* Field tags (for use in manual encoding/decoding) */
#define LithiumMd5Payload_checksum_tag           1

/* Struct field encoding specification for nanopb */
extern const pb_field_t LithiumMd5Payload_fields[2];

/* Maximum encoded size of messages (where known) */
#define LithiumMd5Payload_size                   18

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define LITHIUMMD5PAYLOAD_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
