/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Sat Sep 22 20:28:34 2018. */

#include "LithiumBeaconPeriodCommandPayload.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const uint32_t LithiumBeaconPeriodCommandPayload_beacon_period_ms_default = 0u;


const pb_field_t LithiumBeaconPeriodCommandPayload_fields[2] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, LithiumBeaconPeriodCommandPayload, beacon_period_ms, beacon_period_ms, &LithiumBeaconPeriodCommandPayload_beacon_period_ms_default),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
