/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Sat Aug 11 11:05:50 2018. */

#include "LithiumFastPaCommand.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t LithiumFastPaCommand_fields[2] = {
    PB_FIELD(  1, FIXED32 , REQUIRED, STATIC  , FIRST, LithiumFastPaCommand, pa_level, pa_level, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
