/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.1 at Tue Oct 30 15:36:15 2018. */

#ifndef PB_LITHIUMBEACONPERIODUPLINKPAYLOAD_PB_H_INCLUDED
#define PB_LITHIUMBEACONPERIODUPLINKPAYLOAD_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _LithiumBeaconPeriodUplinkPayload {
    uint32_t beacon_period_ms;
/* @@protoc_insertion_point(struct:LithiumBeaconPeriodUplinkPayload) */
} LithiumBeaconPeriodUplinkPayload;

/* Default values for struct fields */
extern const uint32_t LithiumBeaconPeriodUplinkPayload_beacon_period_ms_default;

/* Initializer values for message structs */
#define LithiumBeaconPeriodUplinkPayload_init_default {0u}
#define LithiumBeaconPeriodUplinkPayload_init_zero {0}

/* Field tags (for use in manual encoding/decoding) */
#define LithiumBeaconPeriodUplinkPayload_beacon_period_ms_tag 1

/* Struct field encoding specification for nanopb */
extern const pb_field_t LithiumBeaconPeriodUplinkPayload_fields[2];

/* Maximum encoded size of messages (where known) */
#define LithiumBeaconPeriodUplinkPayload_size    6

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define LITHIUMBEACONPERIODUPLINKPAYLOAD_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
