/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.1 at Thu Aug 02 10:53:34 2018. */

#ifndef PB_LITHIUMBEACONPERIOD_PB_H_INCLUDED
#define PB_LITHIUMBEACONPERIOD_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _LithiumBeaconPeriod {
    uint32_t beacon_period_ms;
/* @@protoc_insertion_point(struct:LithiumBeaconPeriod) */
} LithiumBeaconPeriod;

/* Default values for struct fields */

/* Initializer values for message structs */
#define LithiumBeaconPeriod_init_default         {0}
#define LithiumBeaconPeriod_init_zero            {0}

/* Field tags (for use in manual encoding/decoding) */
#define LithiumBeaconPeriod_beacon_period_ms_tag 1

/* Struct field encoding specification for nanopb */
extern const pb_field_t LithiumBeaconPeriod_fields[2];

/* Maximum encoded size of messages (where known) */
#define LithiumBeaconPeriod_size                 5

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define LITHIUMBEACONPERIOD_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
