/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.1 at Sat Sep 22 20:28:34 2018. */

#ifndef PB_LITHIUMENABLECOMMANDPAYLOAD_PB_H_INCLUDED
#define PB_LITHIUMENABLECOMMANDPAYLOAD_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _LithiumEnableCommandPayload {
    bool should_transmit;
/* @@protoc_insertion_point(struct:LithiumEnableCommandPayload) */
} LithiumEnableCommandPayload;

/* Default values for struct fields */
extern const bool LithiumEnableCommandPayload_should_transmit_default;

/* Initializer values for message structs */
#define LithiumEnableCommandPayload_init_default {true}
#define LithiumEnableCommandPayload_init_zero    {0}

/* Field tags (for use in manual encoding/decoding) */
#define LithiumEnableCommandPayload_should_transmit_tag 1

/* Struct field encoding specification for nanopb */
extern const pb_field_t LithiumEnableCommandPayload_fields[2];

/* Maximum encoded size of messages (where known) */
#define LithiumEnableCommandPayload_size         2

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define LITHIUMENABLECOMMANDPAYLOAD_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
