/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.1 at Tue Oct 30 15:36:24 2018. */

#ifndef PB_LITHIUMFASTPAUPLINKPAYLOAD_PB_H_INCLUDED
#define PB_LITHIUMFASTPAUPLINKPAYLOAD_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _LithiumFastPaUplinkPayload {
    uint32_t pa_level;
/* @@protoc_insertion_point(struct:LithiumFastPaUplinkPayload) */
} LithiumFastPaUplinkPayload;

/* Default values for struct fields */
extern const uint32_t LithiumFastPaUplinkPayload_pa_level_default;

/* Initializer values for message structs */
#define LithiumFastPaUplinkPayload_init_default  {0u}
#define LithiumFastPaUplinkPayload_init_zero     {0}

/* Field tags (for use in manual encoding/decoding) */
#define LithiumFastPaUplinkPayload_pa_level_tag  1

/* Struct field encoding specification for nanopb */
extern const pb_field_t LithiumFastPaUplinkPayload_fields[2];

/* Maximum encoded size of messages (where known) */
#define LithiumFastPaUplinkPayload_size          6

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define LITHIUMFASTPAUPLINKPAYLOAD_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
