/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Thu Aug 02 10:53:34 2018. */

#include "LithiumBeaconPeriod.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t LithiumBeaconPeriod_fields[2] = {
    PB_FIELD(  1, FIXED32 , REQUIRED, STATIC  , FIRST, LithiumBeaconPeriod, beacon_period_ms, beacon_period_ms, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
