/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Sat Sep 22 20:28:34 2018. */

#include "LithiumEnableCommandPayload.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const bool LithiumEnableCommandPayload_should_transmit_default = true;


const pb_field_t LithiumEnableCommandPayload_fields[2] = {
    PB_FIELD(  1, BOOL    , REQUIRED, STATIC  , FIRST, LithiumEnableCommandPayload, should_transmit, should_transmit, &LithiumEnableCommandPayload_should_transmit_default),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
