/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Tue Oct 30 09:37:32 2018. */

#include "LithiumMd5Payload.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t LithiumMd5Payload_fields[2] = {
    PB_FIELD(  1, FIXED_LENGTH_BYTES, REQUIRED, STATIC  , FIRST, LithiumMd5Payload, checksum, checksum, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
