/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Wed Apr 18 18:47:04 2018. */

#include "LithiumOnOffState.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t LithiumOnOffState_fields[2] = {
    PB_FIELD(  1, BOOL    , REQUIRED, STATIC  , FIRST, LithiumOnOffState, shouldTransmit, shouldTransmit, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
