/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 at Mon Aug 13 17:24:48 2018. */

#ifndef PB_PWMOUTPUTREADING_PB_H_INCLUDED
#define PB_PWMOUTPUTREADING_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _PwmOutputReading {
    double x;
    double y;
    double z;
    uint64_t timestamp_millis_unix_epoch;
/* @@protoc_insertion_point(struct:PwmOutputReading) */
} PwmOutputReading;

/* Default values for struct fields */

/* Initializer values for message structs */
#define PwmOutputReading_init_default            {0, 0, 0, 0}
#define PwmOutputReading_init_zero               {0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define PwmOutputReading_x_tag                   1
#define PwmOutputReading_y_tag                   2
#define PwmOutputReading_z_tag                   3
#define PwmOutputReading_timestamp_millis_unix_epoch_tag 4

/* Struct field encoding specification for nanopb */
extern const pb_field_t PwmOutputReading_fields[5];

/* Maximum encoded size of messages (where known) */
#define PwmOutputReading_size                    36

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define PWMOUTPUTREADING_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
