/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Wed Oct 31 16:22:14 2018. */

#include "QuerySectionsUplinkPayload.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const bool QuerySectionsUplinkPayload_queried_default = true;


const pb_field_t QuerySectionsUplinkPayload_fields[2] = {
    PB_FIELD(  1, BOOL    , REQUIRED, STATIC  , FIRST, QuerySectionsUplinkPayload, queried, queried, &QuerySectionsUplinkPayload_queried_default),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
