/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.1 at Wed Oct 31 16:22:14 2018. */

#ifndef PB_QUERYSECTIONSUPLINKPAYLOAD_PB_H_INCLUDED
#define PB_QUERYSECTIONSUPLINKPAYLOAD_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _QuerySectionsUplinkPayload {
    bool queried;
/* @@protoc_insertion_point(struct:QuerySectionsUplinkPayload) */
} QuerySectionsUplinkPayload;

/* Default values for struct fields */
extern const bool QuerySectionsUplinkPayload_queried_default;

/* Initializer values for message structs */
#define QuerySectionsUplinkPayload_init_default  {true}
#define QuerySectionsUplinkPayload_init_zero     {0}

/* Field tags (for use in manual encoding/decoding) */
#define QuerySectionsUplinkPayload_queried_tag   1

/* Struct field encoding specification for nanopb */
extern const pb_field_t QuerySectionsUplinkPayload_fields[2];

/* Maximum encoded size of messages (where known) */
#define QuerySectionsUplinkPayload_size          2

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define QUERYSECTIONSUPLINKPAYLOAD_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
