/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Sat Nov 24 16:37:29 2018. */

#include "ResetInfoContainerReading.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const uint32_t ResetInfoContainerReading_most_recent_reset_cause_default = 48059u;
const uint32_t ResetInfoContainerReading_most_recent_reset_message_default = 0u;
const uint32_t ResetInfoContainerReading_num_resets_default = 0u;
const ResetInfoContainerReading_num_resets_of_cause_t ResetInfoContainerReading_num_resets_of_cause_default = {0, {0}};
const ResetInfoContainerReading_num_resets_with_message_t ResetInfoContainerReading_num_resets_with_message_default = {0, {0}};
const uint32_t ResetInfoContainerReading_first_wakeup_default = 0u;
const bool ResetInfoContainerReading_expected_reset_default = false;
const uint64_t ResetInfoContainerReading_timestamp_ms_default = 0ull;


const pb_field_t ResetInfoContainerReading_fields[9] = {
    PB_FIELD(  1, FIXED32 , REQUIRED, STATIC  , FIRST, ResetInfoContainerReading, most_recent_reset_cause, most_recent_reset_cause, &ResetInfoContainerReading_most_recent_reset_cause_default),
    PB_FIELD(  2, FIXED32 , REQUIRED, STATIC  , OTHER, ResetInfoContainerReading, most_recent_reset_message, most_recent_reset_cause, &ResetInfoContainerReading_most_recent_reset_message_default),
    PB_FIELD(  3, FIXED32 , REQUIRED, STATIC  , OTHER, ResetInfoContainerReading, num_resets, most_recent_reset_message, &ResetInfoContainerReading_num_resets_default),
    PB_FIELD(  4, BYTES   , REQUIRED, STATIC  , OTHER, ResetInfoContainerReading, num_resets_of_cause, num_resets, &ResetInfoContainerReading_num_resets_of_cause_default),
    PB_FIELD(  5, BYTES   , REQUIRED, STATIC  , OTHER, ResetInfoContainerReading, num_resets_with_message, num_resets_of_cause, &ResetInfoContainerReading_num_resets_with_message_default),
    PB_FIELD(  6, FIXED32 , REQUIRED, STATIC  , OTHER, ResetInfoContainerReading, first_wakeup, num_resets_with_message, &ResetInfoContainerReading_first_wakeup_default),
    PB_FIELD(  7, BOOL    , REQUIRED, STATIC  , OTHER, ResetInfoContainerReading, expected_reset, first_wakeup, &ResetInfoContainerReading_expected_reset_default),
    PB_FIELD(  8, FIXED64 , REQUIRED, STATIC  , OTHER, ResetInfoContainerReading, timestamp_ms, expected_reset, &ResetInfoContainerReading_timestamp_ms_default),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
