/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.1 at Sat Nov 24 16:37:29 2018. */

#ifndef PB_RESETINFOCONTAINERREADING_PB_H_INCLUDED
#define PB_RESETINFOCONTAINERREADING_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(11) ResetInfoContainerReading_num_resets_of_cause_t;
typedef PB_BYTES_ARRAY_T(6) ResetInfoContainerReading_num_resets_with_message_t;
typedef struct _ResetInfoContainerReading {
    uint32_t most_recent_reset_cause;
    uint32_t most_recent_reset_message;
    uint32_t num_resets;
    ResetInfoContainerReading_num_resets_of_cause_t num_resets_of_cause;
    ResetInfoContainerReading_num_resets_with_message_t num_resets_with_message;
    uint32_t first_wakeup;
    bool expected_reset;
    uint64_t timestamp_ms;
/* @@protoc_insertion_point(struct:ResetInfoContainerReading) */
} ResetInfoContainerReading;

/* Default values for struct fields */
extern const uint32_t ResetInfoContainerReading_most_recent_reset_cause_default;
extern const uint32_t ResetInfoContainerReading_most_recent_reset_message_default;
extern const uint32_t ResetInfoContainerReading_num_resets_default;
extern const ResetInfoContainerReading_num_resets_of_cause_t ResetInfoContainerReading_num_resets_of_cause_default;
extern const ResetInfoContainerReading_num_resets_with_message_t ResetInfoContainerReading_num_resets_with_message_default;
extern const uint32_t ResetInfoContainerReading_first_wakeup_default;
extern const bool ResetInfoContainerReading_expected_reset_default;
extern const uint64_t ResetInfoContainerReading_timestamp_ms_default;

/* Initializer values for message structs */
#define ResetInfoContainerReading_init_default   {48059u, 0u, 0u, {0, {0}}, {0, {0}}, 0u, false, 0ull}
#define ResetInfoContainerReading_init_zero      {0, 0, 0, {0, {0}}, {0, {0}}, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define ResetInfoContainerReading_most_recent_reset_cause_tag 1
#define ResetInfoContainerReading_most_recent_reset_message_tag 2
#define ResetInfoContainerReading_num_resets_tag 3
#define ResetInfoContainerReading_num_resets_of_cause_tag 4
#define ResetInfoContainerReading_num_resets_with_message_tag 5
#define ResetInfoContainerReading_first_wakeup_tag 6
#define ResetInfoContainerReading_expected_reset_tag 7
#define ResetInfoContainerReading_timestamp_ms_tag 8

/* Struct field encoding specification for nanopb */
extern const pb_field_t ResetInfoContainerReading_fields[9];

/* Maximum encoded size of messages (where known) */
#define ResetInfoContainerReading_size           52

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define RESETINFOCONTAINERREADING_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
