/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Wed Oct 31 16:22:09 2018. */

#include "SectionUplinkPayload.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t SectionUplinkPayload_fields[5] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, SectionUplinkPayload, command_code, command_code, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, SectionUplinkPayload, start_index, command_code, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, SectionUplinkPayload, end_index, start_index, 0),
    PB_FIELD(  4, BYTES   , REQUIRED, STATIC  , OTHER, SectionUplinkPayload, section, end_index, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
