/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Fri Nov 23 16:44:54 2018. */

#include "SetBootStatePayload.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const uint32_t SetBootStatePayload_boot_state_default = 0u;


const pb_field_t SetBootStatePayload_fields[2] = {
    PB_FIELD(  1, FIXED32 , REQUIRED, STATIC  , FIRST, SetBootStatePayload, boot_state, boot_state, &SetBootStatePayload_boot_state_default),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
