/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.1 at Fri Nov 23 16:44:54 2018. */

#ifndef PB_SETBOOTSTATEPAYLOAD_PB_H_INCLUDED
#define PB_SETBOOTSTATEPAYLOAD_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _SetBootStatePayload {
    uint32_t boot_state;
/* @@protoc_insertion_point(struct:SetBootStatePayload) */
} SetBootStatePayload;

/* Default values for struct fields */
extern const uint32_t SetBootStatePayload_boot_state_default;

/* Initializer values for message structs */
#define SetBootStatePayload_init_default         {0u}
#define SetBootStatePayload_init_zero            {0}

/* Field tags (for use in manual encoding/decoding) */
#define SetBootStatePayload_boot_state_tag       1

/* Struct field encoding specification for nanopb */
extern const pb_field_t SetBootStatePayload_fields[2];

/* Maximum encoded size of messages (where known) */
#define SetBootStatePayload_size                 5

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define SETBOOTSTATEPAYLOAD_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
