/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Fri Nov 23 20:12:10 2018. */

#include "SetIChargePayload.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const uint32_t SetIChargePayload_bms_id_default = 0u;
const uint32_t SetIChargePayload_i_charge_index_default = 0u;


const pb_field_t SetIChargePayload_fields[3] = {
    PB_FIELD(  1, FIXED32 , REQUIRED, STATIC  , FIRST, SetIChargePayload, bms_id, bms_id, &SetIChargePayload_bms_id_default),
    PB_FIELD(  2, FIXED32 , REQUIRED, STATIC  , OTHER, SetIChargePayload, i_charge_index, bms_id, &SetIChargePayload_i_charge_index_default),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
