/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Fri Mar 23 00:43:39 2018. */

#include "StateMachineStateReading.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t StateMachineStateReading_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, StateMachineStateReading, state, state, 0),
    PB_FIELD(  2, FIXED64 , REQUIRED, STATIC  , OTHER, StateMachineStateReading, timestamp_millis_unix_epoch, state, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
