/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Thu Dec  6 00:04:34 2018. */

#include "SystemConfigurationUplinkPayload.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const bool SystemConfigurationUplinkPayload_eps_board_available_default = true;
const bool SystemConfigurationUplinkPayload_cdh_board_available_default = true;
const bool SystemConfigurationUplinkPayload_fs_board_available_default = true;
const bool SystemConfigurationUplinkPayload_tcom_board_available_default = true;
const bool SystemConfigurationUplinkPayload_utilities_board_available_default = true;
const bool SystemConfigurationUplinkPayload_x_pos_available_default = true;
const bool SystemConfigurationUplinkPayload_x_neg_available_default = true;
const bool SystemConfigurationUplinkPayload_y_pos_available_default = true;
const bool SystemConfigurationUplinkPayload_y_neg_available_default = true;
const bool SystemConfigurationUplinkPayload_z_pos_available_default = true;
const bool SystemConfigurationUplinkPayload_z_neg_available_default = true;
const bool SystemConfigurationUplinkPayload_i2c_available_default = true;
const bool SystemConfigurationUplinkPayload_sd_card_available_default = true;
const bool SystemConfigurationUplinkPayload_bms_available_default = true;
const bool SystemConfigurationUplinkPayload_antenna_available_default = false;
const bool SystemConfigurationUplinkPayload_eeprom_available_default = false;
const bool SystemConfigurationUplinkPayload_enter_deep_sleep_on_startup_default = false;
const bool SystemConfigurationUplinkPayload_enter_limp_mode_on_startup_default = false;
const bool SystemConfigurationUplinkPayload_deploy_antenna_default = false;
const bool SystemConfigurationUplinkPayload_instant_deployment_waits_default = true;
const bool SystemConfigurationUplinkPayload_format_sd_on_startup_default = false;
const uint32_t SystemConfigurationUplinkPayload_beacon_wait_ms_default = 300000u;
const uint32_t SystemConfigurationUplinkPayload_ejection_wait_ms_default = 300000u;
const uint64_t SystemConfigurationUplinkPayload_time_source_deploy_ms_default = 0ull;
const bool SystemConfigurationUplinkPayload_lithium_transmit_only_when_ground_commanded_default = false;
const uint32_t SystemConfigurationUplinkPayload_nominal_lithium_power_level_default = 140u;
const bool SystemConfigurationUplinkPayload_uplink_fec_enabled_default = true;
const bool SystemConfigurationUplinkPayload_downlink_fec_enabled_default = false;
const bool SystemConfigurationUplinkPayload_check_hmac_default_default = true;
const bool SystemConfigurationUplinkPayload_check_sequence_default_default = false;
const bool SystemConfigurationUplinkPayload_log_i2c_default = false;
const bool SystemConfigurationUplinkPayload_log_to_uart_default = true;
const bool SystemConfigurationUplinkPayload_log_to_sd_default = true;
const bool SystemConfigurationUplinkPayload_hil_available_default = false;
const bool SystemConfigurationUplinkPayload_ditl_mode_default = false;
const bool SystemConfigurationUplinkPayload_verbose_logging_default = false;
const bool SystemConfigurationUplinkPayload_reboot_on_top_level_exception_default = true;
const uint32_t SystemConfigurationUplinkPayload_nominal_beacon_period_ms_default = 10000u;
const uint32_t SystemConfigurationUplinkPayload_orientation_control_loop_period_micros_default = 1000000u;
const uint32_t SystemConfigurationUplinkPayload_health_check_period_ms_default = 1100u;
const uint64_t SystemConfigurationUplinkPayload_antenna_burn_check_interval_ms_default = 60000ull;
const uint32_t SystemConfigurationUplinkPayload_time_update_period_ms_default = 1000u;
const uint32_t SystemConfigurationUplinkPayload_i_charge_hold_time_ms_default = 5000u;
const uint32_t SystemConfigurationUplinkPayload_i_charge_hold_poll_ms_default = 200u;
const uint32_t SystemConfigurationUplinkPayload_solar_power_recovery_time_ms_default = 300u;
const uint32_t SystemConfigurationUplinkPayload_initial_i_charge_index_default = 1u;
const uint64_t SystemConfigurationUplinkPayload_half_orbit_period_ms_default = 2790000ull;
const uint64_t SystemConfigurationUplinkPayload_initial_antenna_burn_interval_ms_default = 4790000ull;
const uint64_t SystemConfigurationUplinkPayload_backup_antenna_burn_interval_ms_default = 8370000ull;
const float SystemConfigurationUplinkPayload_antenna_burn_interval_multiplier_default = 2.5;
const bool SystemConfigurationUplinkPayload_run_magnetorquers_at_constant_power_default = true;
const float SystemConfigurationUplinkPayload_magnetorquer_power_fraction_x_default = 0.2;
const float SystemConfigurationUplinkPayload_magnetorquer_power_fraction_y_default = 0.2;
const float SystemConfigurationUplinkPayload_magnetorquer_power_fraction_z_default = 0.2;
const double SystemConfigurationUplinkPayload_max_magnetorquer_dipole_1_default = 0.2;
const double SystemConfigurationUplinkPayload_max_magnetorquer_dipole_2_default = 0.2;
const double SystemConfigurationUplinkPayload_max_magnetorquer_dipole_3_default = 0.2;
const double SystemConfigurationUplinkPayload_orientation_control_power_level_default = 0.2;
const uint32_t SystemConfigurationUplinkPayload_checksum_default = 0u;


const pb_field_t SystemConfigurationUplinkPayload_fields[60] = {
    PB_FIELD(  1, BOOL    , REQUIRED, STATIC  , FIRST, SystemConfigurationUplinkPayload, eps_board_available, eps_board_available, &SystemConfigurationUplinkPayload_eps_board_available_default),
    PB_FIELD(  2, BOOL    , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, cdh_board_available, eps_board_available, &SystemConfigurationUplinkPayload_cdh_board_available_default),
    PB_FIELD(  3, BOOL    , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, fs_board_available, cdh_board_available, &SystemConfigurationUplinkPayload_fs_board_available_default),
    PB_FIELD(  4, BOOL    , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, tcom_board_available, fs_board_available, &SystemConfigurationUplinkPayload_tcom_board_available_default),
    PB_FIELD(  5, BOOL    , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, utilities_board_available, tcom_board_available, &SystemConfigurationUplinkPayload_utilities_board_available_default),
    PB_FIELD(  6, BOOL    , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, x_pos_available, utilities_board_available, &SystemConfigurationUplinkPayload_x_pos_available_default),
    PB_FIELD(  7, BOOL    , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, x_neg_available, x_pos_available, &SystemConfigurationUplinkPayload_x_neg_available_default),
    PB_FIELD(  8, BOOL    , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, y_pos_available, x_neg_available, &SystemConfigurationUplinkPayload_y_pos_available_default),
    PB_FIELD(  9, BOOL    , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, y_neg_available, y_pos_available, &SystemConfigurationUplinkPayload_y_neg_available_default),
    PB_FIELD( 10, BOOL    , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, z_pos_available, y_neg_available, &SystemConfigurationUplinkPayload_z_pos_available_default),
    PB_FIELD( 11, BOOL    , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, z_neg_available, z_pos_available, &SystemConfigurationUplinkPayload_z_neg_available_default),
    PB_FIELD( 12, BOOL    , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, i2c_available, z_neg_available, &SystemConfigurationUplinkPayload_i2c_available_default),
    PB_FIELD( 13, BOOL    , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, sd_card_available, i2c_available, &SystemConfigurationUplinkPayload_sd_card_available_default),
    PB_FIELD( 14, BOOL    , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, bms_available, sd_card_available, &SystemConfigurationUplinkPayload_bms_available_default),
    PB_FIELD( 15, BOOL    , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, antenna_available, bms_available, &SystemConfigurationUplinkPayload_antenna_available_default),
    PB_FIELD( 16, BOOL    , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, eeprom_available, antenna_available, &SystemConfigurationUplinkPayload_eeprom_available_default),
    PB_FIELD( 17, BOOL    , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, enter_deep_sleep_on_startup, eeprom_available, &SystemConfigurationUplinkPayload_enter_deep_sleep_on_startup_default),
    PB_FIELD( 18, BOOL    , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, enter_limp_mode_on_startup, enter_deep_sleep_on_startup, &SystemConfigurationUplinkPayload_enter_limp_mode_on_startup_default),
    PB_FIELD( 19, BOOL    , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, deploy_antenna, enter_limp_mode_on_startup, &SystemConfigurationUplinkPayload_deploy_antenna_default),
    PB_FIELD( 20, BOOL    , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, instant_deployment_waits, deploy_antenna, &SystemConfigurationUplinkPayload_instant_deployment_waits_default),
    PB_FIELD( 21, BOOL    , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, format_sd_on_startup, instant_deployment_waits, &SystemConfigurationUplinkPayload_format_sd_on_startup_default),
    PB_FIELD( 22, FIXED32 , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, beacon_wait_ms, format_sd_on_startup, &SystemConfigurationUplinkPayload_beacon_wait_ms_default),
    PB_FIELD( 23, FIXED32 , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, ejection_wait_ms, beacon_wait_ms, &SystemConfigurationUplinkPayload_ejection_wait_ms_default),
    PB_FIELD( 24, FIXED64 , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, time_source_deploy_ms, ejection_wait_ms, &SystemConfigurationUplinkPayload_time_source_deploy_ms_default),
    PB_FIELD( 25, BOOL    , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, lithium_transmit_only_when_ground_commanded, time_source_deploy_ms, &SystemConfigurationUplinkPayload_lithium_transmit_only_when_ground_commanded_default),
    PB_FIELD( 26, FIXED32 , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, nominal_lithium_power_level, lithium_transmit_only_when_ground_commanded, &SystemConfigurationUplinkPayload_nominal_lithium_power_level_default),
    PB_FIELD( 27, BOOL    , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, uplink_fec_enabled, nominal_lithium_power_level, &SystemConfigurationUplinkPayload_uplink_fec_enabled_default),
    PB_FIELD( 28, BOOL    , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, downlink_fec_enabled, uplink_fec_enabled, &SystemConfigurationUplinkPayload_downlink_fec_enabled_default),
    PB_FIELD( 29, BOOL    , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, check_hmac_default, downlink_fec_enabled, &SystemConfigurationUplinkPayload_check_hmac_default_default),
    PB_FIELD( 30, BOOL    , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, check_sequence_default, check_hmac_default, &SystemConfigurationUplinkPayload_check_sequence_default_default),
    PB_FIELD( 31, BOOL    , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, log_i2c, check_sequence_default, &SystemConfigurationUplinkPayload_log_i2c_default),
    PB_FIELD( 32, BOOL    , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, log_to_uart, log_i2c, &SystemConfigurationUplinkPayload_log_to_uart_default),
    PB_FIELD( 33, BOOL    , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, log_to_sd, log_to_uart, &SystemConfigurationUplinkPayload_log_to_sd_default),
    PB_FIELD( 34, BOOL    , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, hil_available, log_to_sd, &SystemConfigurationUplinkPayload_hil_available_default),
    PB_FIELD( 35, BOOL    , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, ditl_mode, hil_available, &SystemConfigurationUplinkPayload_ditl_mode_default),
    PB_FIELD( 36, BOOL    , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, verbose_logging, ditl_mode, &SystemConfigurationUplinkPayload_verbose_logging_default),
    PB_FIELD( 37, BOOL    , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, reboot_on_top_level_exception, verbose_logging, &SystemConfigurationUplinkPayload_reboot_on_top_level_exception_default),
    PB_FIELD( 38, FIXED32 , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, nominal_beacon_period_ms, reboot_on_top_level_exception, &SystemConfigurationUplinkPayload_nominal_beacon_period_ms_default),
    PB_FIELD( 39, FIXED32 , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, orientation_control_loop_period_micros, nominal_beacon_period_ms, &SystemConfigurationUplinkPayload_orientation_control_loop_period_micros_default),
    PB_FIELD( 40, FIXED32 , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, health_check_period_ms, orientation_control_loop_period_micros, &SystemConfigurationUplinkPayload_health_check_period_ms_default),
    PB_FIELD( 41, FIXED64 , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, antenna_burn_check_interval_ms, health_check_period_ms, &SystemConfigurationUplinkPayload_antenna_burn_check_interval_ms_default),
    PB_FIELD( 42, FIXED32 , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, time_update_period_ms, antenna_burn_check_interval_ms, &SystemConfigurationUplinkPayload_time_update_period_ms_default),
    PB_FIELD( 43, FIXED32 , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, i_charge_hold_time_ms, time_update_period_ms, &SystemConfigurationUplinkPayload_i_charge_hold_time_ms_default),
    PB_FIELD( 44, FIXED32 , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, i_charge_hold_poll_ms, i_charge_hold_time_ms, &SystemConfigurationUplinkPayload_i_charge_hold_poll_ms_default),
    PB_FIELD( 45, FIXED32 , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, solar_power_recovery_time_ms, i_charge_hold_poll_ms, &SystemConfigurationUplinkPayload_solar_power_recovery_time_ms_default),
    PB_FIELD( 46, FIXED32 , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, initial_i_charge_index, solar_power_recovery_time_ms, &SystemConfigurationUplinkPayload_initial_i_charge_index_default),
    PB_FIELD( 47, FIXED64 , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, half_orbit_period_ms, initial_i_charge_index, &SystemConfigurationUplinkPayload_half_orbit_period_ms_default),
    PB_FIELD( 48, FIXED64 , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, initial_antenna_burn_interval_ms, half_orbit_period_ms, &SystemConfigurationUplinkPayload_initial_antenna_burn_interval_ms_default),
    PB_FIELD( 49, FIXED64 , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, backup_antenna_burn_interval_ms, initial_antenna_burn_interval_ms, &SystemConfigurationUplinkPayload_backup_antenna_burn_interval_ms_default),
    PB_FIELD( 50, FLOAT   , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, antenna_burn_interval_multiplier, backup_antenna_burn_interval_ms, &SystemConfigurationUplinkPayload_antenna_burn_interval_multiplier_default),
    PB_FIELD( 51, BOOL    , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, run_magnetorquers_at_constant_power, antenna_burn_interval_multiplier, &SystemConfigurationUplinkPayload_run_magnetorquers_at_constant_power_default),
    PB_FIELD( 52, FLOAT   , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, magnetorquer_power_fraction_x, run_magnetorquers_at_constant_power, &SystemConfigurationUplinkPayload_magnetorquer_power_fraction_x_default),
    PB_FIELD( 53, FLOAT   , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, magnetorquer_power_fraction_y, magnetorquer_power_fraction_x, &SystemConfigurationUplinkPayload_magnetorquer_power_fraction_y_default),
    PB_FIELD( 54, FLOAT   , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, magnetorquer_power_fraction_z, magnetorquer_power_fraction_y, &SystemConfigurationUplinkPayload_magnetorquer_power_fraction_z_default),
    PB_FIELD( 55, DOUBLE  , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, max_magnetorquer_dipole_1, magnetorquer_power_fraction_z, &SystemConfigurationUplinkPayload_max_magnetorquer_dipole_1_default),
    PB_FIELD( 56, DOUBLE  , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, max_magnetorquer_dipole_2, max_magnetorquer_dipole_1, &SystemConfigurationUplinkPayload_max_magnetorquer_dipole_2_default),
    PB_FIELD( 57, DOUBLE  , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, max_magnetorquer_dipole_3, max_magnetorquer_dipole_2, &SystemConfigurationUplinkPayload_max_magnetorquer_dipole_3_default),
    PB_FIELD( 58, DOUBLE  , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, orientation_control_power_level, max_magnetorquer_dipole_3, &SystemConfigurationUplinkPayload_orientation_control_power_level_default),
    PB_FIELD( 59, FIXED32 , REQUIRED, STATIC  , OTHER, SystemConfigurationUplinkPayload, checksum, orientation_control_power_level, &SystemConfigurationUplinkPayload_checksum_default),
    PB_LAST_FIELD
};


/* On some platforms (such as AVR), double is really float.
 * These are not directly supported by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

/* @@protoc_insertion_point(eof) */
