/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Tue Oct 30 15:36:31 2018. */

#include "SystemResetUplinkPayload.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const uint32_t SystemResetUplinkPayload_reset_enable_default = 0u;


const pb_field_t SystemResetUplinkPayload_fields[2] = {
    PB_FIELD(  1, FIXED32 , REQUIRED, STATIC  , FIRST, SystemResetUplinkPayload, reset_enable, reset_enable, &SystemResetUplinkPayload_reset_enable_default),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
