/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.1 at Thu Dec  6 00:04:34 2018. */

#ifndef PB_SYSTEMCONFIGURATIONUPLINKPAYLOAD_PB_H_INCLUDED
#define PB_SYSTEMCONFIGURATIONUPLINKPAYLOAD_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _SystemConfigurationUplinkPayload {
    bool eps_board_available;
    bool cdh_board_available;
    bool fs_board_available;
    bool tcom_board_available;
    bool utilities_board_available;
    bool x_pos_available;
    bool x_neg_available;
    bool y_pos_available;
    bool y_neg_available;
    bool z_pos_available;
    bool z_neg_available;
    bool i2c_available;
    bool sd_card_available;
    bool bms_available;
    bool antenna_available;
    bool eeprom_available;
    bool enter_deep_sleep_on_startup;
    bool enter_limp_mode_on_startup;
    bool deploy_antenna;
    bool instant_deployment_waits;
    bool format_sd_on_startup;
    uint32_t beacon_wait_ms;
    uint32_t ejection_wait_ms;
    uint64_t time_source_deploy_ms;
    bool lithium_transmit_only_when_ground_commanded;
    uint32_t nominal_lithium_power_level;
    bool uplink_fec_enabled;
    bool downlink_fec_enabled;
    bool check_hmac_default;
    bool check_sequence_default;
    bool log_i2c;
    bool log_to_uart;
    bool log_to_sd;
    bool hil_available;
    bool ditl_mode;
    bool verbose_logging;
    bool reboot_on_top_level_exception;
    uint32_t nominal_beacon_period_ms;
    uint32_t orientation_control_loop_period_micros;
    uint32_t health_check_period_ms;
    uint64_t antenna_burn_check_interval_ms;
    uint32_t time_update_period_ms;
    uint32_t i_charge_hold_time_ms;
    uint32_t i_charge_hold_poll_ms;
    uint32_t solar_power_recovery_time_ms;
    uint32_t initial_i_charge_index;
    uint64_t half_orbit_period_ms;
    uint64_t initial_antenna_burn_interval_ms;
    uint64_t backup_antenna_burn_interval_ms;
    float antenna_burn_interval_multiplier;
    bool run_magnetorquers_at_constant_power;
    float magnetorquer_power_fraction_x;
    float magnetorquer_power_fraction_y;
    float magnetorquer_power_fraction_z;
    double max_magnetorquer_dipole_1;
    double max_magnetorquer_dipole_2;
    double max_magnetorquer_dipole_3;
    double orientation_control_power_level;
    uint32_t checksum;
/* @@protoc_insertion_point(struct:SystemConfigurationUplinkPayload) */
} SystemConfigurationUplinkPayload;

/* Default values for struct fields */
extern const bool SystemConfigurationUplinkPayload_eps_board_available_default;
extern const bool SystemConfigurationUplinkPayload_cdh_board_available_default;
extern const bool SystemConfigurationUplinkPayload_fs_board_available_default;
extern const bool SystemConfigurationUplinkPayload_tcom_board_available_default;
extern const bool SystemConfigurationUplinkPayload_utilities_board_available_default;
extern const bool SystemConfigurationUplinkPayload_x_pos_available_default;
extern const bool SystemConfigurationUplinkPayload_x_neg_available_default;
extern const bool SystemConfigurationUplinkPayload_y_pos_available_default;
extern const bool SystemConfigurationUplinkPayload_y_neg_available_default;
extern const bool SystemConfigurationUplinkPayload_z_pos_available_default;
extern const bool SystemConfigurationUplinkPayload_z_neg_available_default;
extern const bool SystemConfigurationUplinkPayload_i2c_available_default;
extern const bool SystemConfigurationUplinkPayload_sd_card_available_default;
extern const bool SystemConfigurationUplinkPayload_bms_available_default;
extern const bool SystemConfigurationUplinkPayload_antenna_available_default;
extern const bool SystemConfigurationUplinkPayload_eeprom_available_default;
extern const bool SystemConfigurationUplinkPayload_enter_deep_sleep_on_startup_default;
extern const bool SystemConfigurationUplinkPayload_enter_limp_mode_on_startup_default;
extern const bool SystemConfigurationUplinkPayload_deploy_antenna_default;
extern const bool SystemConfigurationUplinkPayload_instant_deployment_waits_default;
extern const bool SystemConfigurationUplinkPayload_format_sd_on_startup_default;
extern const uint32_t SystemConfigurationUplinkPayload_beacon_wait_ms_default;
extern const uint32_t SystemConfigurationUplinkPayload_ejection_wait_ms_default;
extern const uint64_t SystemConfigurationUplinkPayload_time_source_deploy_ms_default;
extern const bool SystemConfigurationUplinkPayload_lithium_transmit_only_when_ground_commanded_default;
extern const uint32_t SystemConfigurationUplinkPayload_nominal_lithium_power_level_default;
extern const bool SystemConfigurationUplinkPayload_uplink_fec_enabled_default;
extern const bool SystemConfigurationUplinkPayload_downlink_fec_enabled_default;
extern const bool SystemConfigurationUplinkPayload_check_hmac_default_default;
extern const bool SystemConfigurationUplinkPayload_check_sequence_default_default;
extern const bool SystemConfigurationUplinkPayload_log_i2c_default;
extern const bool SystemConfigurationUplinkPayload_log_to_uart_default;
extern const bool SystemConfigurationUplinkPayload_log_to_sd_default;
extern const bool SystemConfigurationUplinkPayload_hil_available_default;
extern const bool SystemConfigurationUplinkPayload_ditl_mode_default;
extern const bool SystemConfigurationUplinkPayload_verbose_logging_default;
extern const bool SystemConfigurationUplinkPayload_reboot_on_top_level_exception_default;
extern const uint32_t SystemConfigurationUplinkPayload_nominal_beacon_period_ms_default;
extern const uint32_t SystemConfigurationUplinkPayload_orientation_control_loop_period_micros_default;
extern const uint32_t SystemConfigurationUplinkPayload_health_check_period_ms_default;
extern const uint64_t SystemConfigurationUplinkPayload_antenna_burn_check_interval_ms_default;
extern const uint32_t SystemConfigurationUplinkPayload_time_update_period_ms_default;
extern const uint32_t SystemConfigurationUplinkPayload_i_charge_hold_time_ms_default;
extern const uint32_t SystemConfigurationUplinkPayload_i_charge_hold_poll_ms_default;
extern const uint32_t SystemConfigurationUplinkPayload_solar_power_recovery_time_ms_default;
extern const uint32_t SystemConfigurationUplinkPayload_initial_i_charge_index_default;
extern const uint64_t SystemConfigurationUplinkPayload_half_orbit_period_ms_default;
extern const uint64_t SystemConfigurationUplinkPayload_initial_antenna_burn_interval_ms_default;
extern const uint64_t SystemConfigurationUplinkPayload_backup_antenna_burn_interval_ms_default;
extern const float SystemConfigurationUplinkPayload_antenna_burn_interval_multiplier_default;
extern const bool SystemConfigurationUplinkPayload_run_magnetorquers_at_constant_power_default;
extern const float SystemConfigurationUplinkPayload_magnetorquer_power_fraction_x_default;
extern const float SystemConfigurationUplinkPayload_magnetorquer_power_fraction_y_default;
extern const float SystemConfigurationUplinkPayload_magnetorquer_power_fraction_z_default;
extern const double SystemConfigurationUplinkPayload_max_magnetorquer_dipole_1_default;
extern const double SystemConfigurationUplinkPayload_max_magnetorquer_dipole_2_default;
extern const double SystemConfigurationUplinkPayload_max_magnetorquer_dipole_3_default;
extern const double SystemConfigurationUplinkPayload_orientation_control_power_level_default;
extern const uint32_t SystemConfigurationUplinkPayload_checksum_default;

/* Initializer values for message structs */
#define SystemConfigurationUplinkPayload_init_default {true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, true, false, 300000u, 300000u, 0ull, false, 140u, true, false, true, false, false, true, true, false, false, false, true, 10000u, 1000000u, 1100u, 60000ull, 1000u, 5000u, 200u, 300u, 1u, 2790000ull, 4790000ull, 8370000ull, 2.5, true, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0u}
#define SystemConfigurationUplinkPayload_init_zero {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define SystemConfigurationUplinkPayload_eps_board_available_tag 1
#define SystemConfigurationUplinkPayload_cdh_board_available_tag 2
#define SystemConfigurationUplinkPayload_fs_board_available_tag 3
#define SystemConfigurationUplinkPayload_tcom_board_available_tag 4
#define SystemConfigurationUplinkPayload_utilities_board_available_tag 5
#define SystemConfigurationUplinkPayload_x_pos_available_tag 6
#define SystemConfigurationUplinkPayload_x_neg_available_tag 7
#define SystemConfigurationUplinkPayload_y_pos_available_tag 8
#define SystemConfigurationUplinkPayload_y_neg_available_tag 9
#define SystemConfigurationUplinkPayload_z_pos_available_tag 10
#define SystemConfigurationUplinkPayload_z_neg_available_tag 11
#define SystemConfigurationUplinkPayload_i2c_available_tag 12
#define SystemConfigurationUplinkPayload_sd_card_available_tag 13
#define SystemConfigurationUplinkPayload_bms_available_tag 14
#define SystemConfigurationUplinkPayload_antenna_available_tag 15
#define SystemConfigurationUplinkPayload_eeprom_available_tag 16
#define SystemConfigurationUplinkPayload_enter_deep_sleep_on_startup_tag 17
#define SystemConfigurationUplinkPayload_enter_limp_mode_on_startup_tag 18
#define SystemConfigurationUplinkPayload_deploy_antenna_tag 19
#define SystemConfigurationUplinkPayload_instant_deployment_waits_tag 20
#define SystemConfigurationUplinkPayload_format_sd_on_startup_tag 21
#define SystemConfigurationUplinkPayload_beacon_wait_ms_tag 22
#define SystemConfigurationUplinkPayload_ejection_wait_ms_tag 23
#define SystemConfigurationUplinkPayload_time_source_deploy_ms_tag 24
#define SystemConfigurationUplinkPayload_lithium_transmit_only_when_ground_commanded_tag 25
#define SystemConfigurationUplinkPayload_nominal_lithium_power_level_tag 26
#define SystemConfigurationUplinkPayload_uplink_fec_enabled_tag 27
#define SystemConfigurationUplinkPayload_downlink_fec_enabled_tag 28
#define SystemConfigurationUplinkPayload_check_hmac_default_tag 29
#define SystemConfigurationUplinkPayload_check_sequence_default_tag 30
#define SystemConfigurationUplinkPayload_log_i2c_tag 31
#define SystemConfigurationUplinkPayload_log_to_uart_tag 32
#define SystemConfigurationUplinkPayload_log_to_sd_tag 33
#define SystemConfigurationUplinkPayload_hil_available_tag 34
#define SystemConfigurationUplinkPayload_ditl_mode_tag 35
#define SystemConfigurationUplinkPayload_verbose_logging_tag 36
#define SystemConfigurationUplinkPayload_reboot_on_top_level_exception_tag 37
#define SystemConfigurationUplinkPayload_nominal_beacon_period_ms_tag 38
#define SystemConfigurationUplinkPayload_orientation_control_loop_period_micros_tag 39
#define SystemConfigurationUplinkPayload_health_check_period_ms_tag 40
#define SystemConfigurationUplinkPayload_antenna_burn_check_interval_ms_tag 41
#define SystemConfigurationUplinkPayload_time_update_period_ms_tag 42
#define SystemConfigurationUplinkPayload_i_charge_hold_time_ms_tag 43
#define SystemConfigurationUplinkPayload_i_charge_hold_poll_ms_tag 44
#define SystemConfigurationUplinkPayload_solar_power_recovery_time_ms_tag 45
#define SystemConfigurationUplinkPayload_initial_i_charge_index_tag 46
#define SystemConfigurationUplinkPayload_half_orbit_period_ms_tag 47
#define SystemConfigurationUplinkPayload_initial_antenna_burn_interval_ms_tag 48
#define SystemConfigurationUplinkPayload_backup_antenna_burn_interval_ms_tag 49
#define SystemConfigurationUplinkPayload_antenna_burn_interval_multiplier_tag 50
#define SystemConfigurationUplinkPayload_run_magnetorquers_at_constant_power_tag 51
#define SystemConfigurationUplinkPayload_magnetorquer_power_fraction_x_tag 52
#define SystemConfigurationUplinkPayload_magnetorquer_power_fraction_y_tag 53
#define SystemConfigurationUplinkPayload_magnetorquer_power_fraction_z_tag 54
#define SystemConfigurationUplinkPayload_max_magnetorquer_dipole_1_tag 55
#define SystemConfigurationUplinkPayload_max_magnetorquer_dipole_2_tag 56
#define SystemConfigurationUplinkPayload_max_magnetorquer_dipole_3_tag 57
#define SystemConfigurationUplinkPayload_orientation_control_power_level_tag 58
#define SystemConfigurationUplinkPayload_checksum_tag 59

/* Struct field encoding specification for nanopb */
extern const pb_field_t SystemConfigurationUplinkPayload_fields[60];

/* Maximum encoded size of messages (where known) */
#define SystemConfigurationUplinkPayload_size    273

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define SYSTEMCONFIGURATIONUPLINKPAYLOAD_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
