/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Sat Sep 22 20:28:34 2018. */

#include "SystemResetCommand.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const uint32_t SystemResetCommand_reset_enable_default = 0u;


const pb_field_t SystemResetCommand_fields[2] = {
    PB_FIELD(  1, FIXED32 , REQUIRED, STATIC  , FIRST, SystemResetCommand, reset_enable, reset_enable, &SystemResetCommand_reset_enable_default),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
