/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Sat Sep 22 20:28:34 2018. */

#include "TemperatureReading.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const float TemperatureReading_temp_default = -9999;
const uint64_t TemperatureReading_timestamp_ms_default = 0ull;


const pb_field_t TemperatureReading_fields[3] = {
    PB_FIELD(  1, FLOAT   , REQUIRED, STATIC  , FIRST, TemperatureReading, temp, temp, &TemperatureReading_temp_default),
    PB_FIELD(  2, FIXED64 , REQUIRED, STATIC  , OTHER, TemperatureReading, timestamp_ms, temp, &TemperatureReading_timestamp_ms_default),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
