/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Wed May 16 13:29:06 2018. */

#include "TemperatureReading.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t TemperatureReading_fields[3] = {
    PB_FIELD(  1, FLOAT   , REQUIRED, STATIC  , FIRST, TemperatureReading, temp, temp, 0),
    PB_FIELD(  2, FIXED64 , REQUIRED, STATIC  , OTHER, TemperatureReading, timestamp_millis_unix_epoch, temp, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
