/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.1 at Thu Nov 22 17:57:05 2018. */

#ifndef PB_TERMINATEANTENNABURNPAYLOAD_PB_H_INCLUDED
#define PB_TERMINATEANTENNABURNPAYLOAD_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _TerminateAntennaBurnPayload {
    uint32_t terminate_burn;
/* @@protoc_insertion_point(struct:TerminateAntennaBurnPayload) */
} TerminateAntennaBurnPayload;

/* Default values for struct fields */
extern const uint32_t TerminateAntennaBurnPayload_terminate_burn_default;

/* Initializer values for message structs */
#define TerminateAntennaBurnPayload_init_default {0u}
#define TerminateAntennaBurnPayload_init_zero    {0}

/* Field tags (for use in manual encoding/decoding) */
#define TerminateAntennaBurnPayload_terminate_burn_tag 1

/* Struct field encoding specification for nanopb */
extern const pb_field_t TerminateAntennaBurnPayload_fields[2];

/* Maximum encoded size of messages (where known) */
#define TerminateAntennaBurnPayload_size         5

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define TERMINATEANTENNABURNPAYLOAD_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
