/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Thu Nov 22 17:57:05 2018. */

#include "TerminateAntennaBurnPayload.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const uint32_t TerminateAntennaBurnPayload_terminate_burn_default = 0u;


const pb_field_t TerminateAntennaBurnPayload_fields[2] = {
    PB_FIELD(  1, FIXED32 , REQUIRED, STATIC  , FIRST, TerminateAntennaBurnPayload, terminate_burn, terminate_burn, &TerminateAntennaBurnPayload_terminate_burn_default),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
