/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Wed Apr  4 22:12:00 2018. */

#include "Time.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Time_fields[2] = {
    PB_FIELD(  1, FIXED64 , REQUIRED, STATIC  , FIRST, Time, timestamp_millis_unix_epoch, timestamp_millis_unix_epoch, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
