/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Sat Sep 22 20:28:34 2018. */

#include "Time.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const uint64_t Time_timestamp_ms_default = 0ull;
const bool Time_is_valid_default = false;


const pb_field_t Time_fields[3] = {
    PB_FIELD(  1, FIXED64 , REQUIRED, STATIC  , FIRST, Time, timestamp_ms, timestamp_ms, &Time_timestamp_ms_default),
    PB_FIELD(  2, BOOL    , REQUIRED, STATIC  , OTHER, Time, is_valid, timestamp_ms, &Time_is_valid_default),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
