/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Fri Apr 13 20:46:22 2018. */

#include "Tle.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Tle_fields[9] = {
    PB_FIELD(  1, DOUBLE  , REQUIRED, STATIC  , FIRST, Tle, mean_motion, mean_motion, 0),
    PB_FIELD(  2, DOUBLE  , REQUIRED, STATIC  , OTHER, Tle, mean_anomaly, mean_motion, 0),
    PB_FIELD(  3, DOUBLE  , REQUIRED, STATIC  , OTHER, Tle, inclination, mean_anomaly, 0),
    PB_FIELD(  4, DOUBLE  , REQUIRED, STATIC  , OTHER, Tle, raan, inclination, 0),
    PB_FIELD(  5, DOUBLE  , REQUIRED, STATIC  , OTHER, Tle, bstar_drag, raan, 0),
    PB_FIELD(  6, DOUBLE  , REQUIRED, STATIC  , OTHER, Tle, epoch, bstar_drag, 0),
    PB_FIELD(  7, DOUBLE  , REQUIRED, STATIC  , OTHER, Tle, eccentricity_1e7, epoch, 0),
    PB_FIELD(  8, DOUBLE  , REQUIRED, STATIC  , OTHER, Tle, argument_of_perigee, eccentricity_1e7, 0),
    PB_LAST_FIELD
};


/* On some platforms (such as AVR), double is really float.
 * These are not directly supported by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

/* @@protoc_insertion_point(eof) */
