/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Sat Sep 22 20:28:34 2018. */

#include "Tle.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const double Tle_mean_motion_default = -9999;
const double Tle_mean_anomaly_default = -9999;
const double Tle_inclination_default = -9999;
const double Tle_raan_default = -9999;
const double Tle_bstar_drag_default = -9999;
const double Tle_epoch_default = -9999;
const double Tle_eccentricity_1e7_default = -9999;
const double Tle_argument_of_perigee_default = -9999;


const pb_field_t Tle_fields[9] = {
    PB_FIELD(  1, DOUBLE  , REQUIRED, STATIC  , FIRST, Tle, mean_motion, mean_motion, &Tle_mean_motion_default),
    PB_FIELD(  2, DOUBLE  , REQUIRED, STATIC  , OTHER, Tle, mean_anomaly, mean_motion, &Tle_mean_anomaly_default),
    PB_FIELD(  3, DOUBLE  , REQUIRED, STATIC  , OTHER, Tle, inclination, mean_anomaly, &Tle_inclination_default),
    PB_FIELD(  4, DOUBLE  , REQUIRED, STATIC  , OTHER, Tle, raan, inclination, &Tle_raan_default),
    PB_FIELD(  5, DOUBLE  , REQUIRED, STATIC  , OTHER, Tle, bstar_drag, raan, &Tle_bstar_drag_default),
    PB_FIELD(  6, DOUBLE  , REQUIRED, STATIC  , OTHER, Tle, epoch, bstar_drag, &Tle_epoch_default),
    PB_FIELD(  7, DOUBLE  , REQUIRED, STATIC  , OTHER, Tle, eccentricity_1e7, epoch, &Tle_eccentricity_1e7_default),
    PB_FIELD(  8, DOUBLE  , REQUIRED, STATIC  , OTHER, Tle, argument_of_perigee, eccentricity_1e7, &Tle_argument_of_perigee_default),
    PB_LAST_FIELD
};


/* On some platforms (such as AVR), double is really float.
 * These are not directly supported by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

/* @@protoc_insertion_point(eof) */
