/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 at Tue Nov 13 01:18:56 2018. */

#ifndef PB_TLE_PB_H_INCLUDED
#define PB_TLE_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _Tle {
    double mean_motion;
    double mean_anomaly;
    double inclination;
    double raan;
    double bstar_drag;
    double epoch;
    double eccentricity_1e7;
    double argument_of_perigee;
    uint64_t time_since_epoch_ms;
/* @@protoc_insertion_point(struct:Tle) */
} Tle;

/* Default values for struct fields */
extern const double Tle_mean_motion_default;
extern const double Tle_mean_anomaly_default;
extern const double Tle_inclination_default;
extern const double Tle_raan_default;
extern const double Tle_bstar_drag_default;
extern const double Tle_epoch_default;
extern const double Tle_eccentricity_1e7_default;
extern const double Tle_argument_of_perigee_default;
extern const uint64_t Tle_time_since_epoch_ms_default;

/* Initializer values for message structs */
#define Tle_init_default                         {-9999, -9999, -9999, -9999, -9999, -9999, -9999, -9999, 0ull}
#define Tle_init_zero                            {0, 0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Tle_mean_motion_tag                      1
#define Tle_mean_anomaly_tag                     2
#define Tle_inclination_tag                      3
#define Tle_raan_tag                             4
#define Tle_bstar_drag_tag                       5
#define Tle_epoch_tag                            6
#define Tle_eccentricity_1e7_tag                 7
#define Tle_argument_of_perigee_tag              8
#define Tle_time_since_epoch_ms_tag              9

/* Struct field encoding specification for nanopb */
extern const pb_field_t Tle_fields[10];

/* Maximum encoded size of messages (where known) */
#define Tle_size                                 81

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define TLE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
