/* AUTOGENERATED FILE. DO NOT EDIT. */

#ifndef TEST_RUNNERS_ANTENNA_TESTS_H_
#define TEST_RUNNERS_ANTENNA_TESTS_H_

#include "unity.h"
#include <Board.h>
#include <src/config/unit_tests.h>
#include <src/messages/antenna_message.h>
#include <src/telecomms/antenna.h>
#include <test_runners/antenna_tests.h>
#include <src/util/memory_troubleshooter.h>
#include <external/etl/exception.h>

void TestSafeDeploy(void);

#endif  // TEST_RUNNERS_ANTENNA_TESTS_H_
