/* AUTOGENERATED FILE. DO NOT EDIT. */

#ifndef TEST_RUNNERS_B_DOT_CONTROLLER_TESTS_H_
#define TEST_RUNNERS_B_DOT_CONTROLLER_TESTS_H_

#include "unity.h"
#include <src/adcs/controllers/b_dot_controller.h>
#include <test_runners/b_dot_controller_tests.h>
#include <src/util/memory_troubleshooter.h>
#include <external/etl/exception.h>

void TestControl(void);

#endif  // TEST_RUNNERS_B_DOT_CONTROLLER_TESTS_H_
