/* AUTOGENERATED FILE. DO NOT EDIT. */

#ifndef TEST_RUNNERS_B_DOT_ESTIMATOR_TESTS_H_
#define TEST_RUNNERS_B_DOT_ESTIMATOR_TESTS_H_

#include "unity.h"
#include <src/adcs/state_estimators/b_dot_estimator.h>
#include <test_runners/b_dot_estimator_tests.h>
#include <src/util/memory_troubleshooter.h>
#include <external/etl/exception.h>

void TestBDotEstimator(void);

#endif  // TEST_RUNNERS_B_DOT_ESTIMATOR_TESTS_H_
