/* AUTOGENERATED FILE. DO NOT EDIT. */

#ifndef TEST_RUNNERS_BMS_TESTS_H_
#define TEST_RUNNERS_BMS_TESTS_H_

#include "unity.h"
#include <Board.h>
#include <external/etl/array.h>
#include <src/config/unit_tests.h>
#include <src/i2c/bms/bms.h>
#include <src/i2c/i2c.h>
#include <src/sensors/i2c_measurable_manager.h>
#include <test_runners/bms_tests.h>
#include <ti/sysbios/knl/Task.h>
#include <src/util/memory_troubleshooter.h>
#include <external/etl/exception.h>

void TestBms(void);
void TestBmsDieTemperatureRead(void);
void TestBmsBatteryTemperatureRead(void);
void TestJeitaRegion(void);

#endif  // TEST_RUNNERS_BMS_TESTS_H_
