/* AUTOGENERATED FILE. DO NOT EDIT. */

#ifndef TEST_RUNNERS_BMS_TESTS_H_
#define TEST_RUNNERS_BMS_TESTS_H_

#include "unity.h"
#include <test_runners/bms_tests.h>

void TestBms(void);

#endif  // TEST_RUNNERS_BMS_TESTS_H_
