/* AUTOGENERATED FILE. DO NOT EDIT. */

#ifndef TEST_RUNNERS_CACHE_WRITE_BACK_TESTS_H_
#define TEST_RUNNERS_CACHE_WRITE_BACK_TESTS_H_

#include "unity.h"
#include <external/etl/exception.h>
#include <external/nanopb/pb_decode.h>
#include <external/nanopb/pb_encode.h>
#include <src/config/unit_tests.h>
#include <src/database/circular_buffer_nanopb.h>
#include <src/database/sd_card.h>
#include <src/messages/TemperatureReading.pb.h>
#include <src/sensors/i2c_measurable_manager.h>
#include <src/sensors/measurable_id.h>
#include <src/sensors/runnable_cache_write_back.h>
#include <stdio.h>
#include <src/util/memory_troubleshooter.h>
#include <external/etl/exception.h>

void TestCacheWriteBack(void);

#endif  // TEST_RUNNERS_CACHE_WRITE_BACK_TESTS_H_
