/* AUTOGENERATED FILE. DO NOT EDIT. */

#ifndef TEST_RUNNERS_CIRCULAR_BUFFER_NANOPB_TESTS_H_
#define TEST_RUNNERS_CIRCULAR_BUFFER_NANOPB_TESTS_H_

#include "unity.h"
#include <src/database/circular_buffer_nanopb.h>
<<<<<<< HEAD
#include <src/messages/MagnetometerReading.pb.h>
#include <test_runners/circular_buffer_nanopb_tests.h>
=======
#include <test_runners/circular_buffer_nanopb_tests.h>
#include <src/messages/MagnetometerReading.pb.h>
>>>>>>> Detumbling branch to get detumbling working until it works
#include <src/util/memory_troubleshooter.h>
#include <external/etl/exception.h>

void TestWriteAndRead(void);

#endif  // TEST_RUNNERS_CIRCULAR_BUFFER_NANOPB_TESTS_H_
