/* AUTOGENERATED FILE. DO NOT EDIT. */

#ifndef TEST_RUNNERS_DATABASE_TESTS_H_
#define TEST_RUNNERS_DATABASE_TESTS_H_

#include "unity.h"
#include <src/database/HammingCoder.h>
#include <src/util/memory_troubleshooter.h>

void TestHamming(void);

#endif  // TEST_RUNNERS_DATABASE_TESTS_H_
