/* AUTOGENERATED FILE. DO NOT EDIT. */

#ifndef TEST_RUNNERS_DEBUG_INTERFACE_TESTS_H_
#define TEST_RUNNERS_DEBUG_INTERFACE_TESTS_H_

#include "unity.h"
#include <src/debug_interface/debug_stream.h>
#include <src/debug_interface/runnable_debug_stream.h>
#include <src/messages/serialised_message.h>
#include <src/messages/temperature_message.h>
#include <src/messages/test_container_message.h>
#include <src/messages/test_message.h>
#include <src/util/message_codes.h>
#include <test_runners/debug_interface_tests.h>

void TestTestDebugMessageQueue(void);
void TestTempDebugMessageQueue(void);
void TestContainerDebugMessageQueue(void);
void TestMixedDebugMessageQueue(void);

#endif  // TEST_RUNNERS_DEBUG_INTERFACE_TESTS_H_
