/* AUTOGENERATED FILE. DO NOT EDIT. */

#ifndef TEST_RUNNERS_DEBUG_INTERFACE_TESTS_H_
#define TEST_RUNNERS_DEBUG_INTERFACE_TESTS_H_

#include "unity.h"
#include <external/etl/exception.h>
#include <external/nanopb/pb_decode.h>
#include <external/nanopb/pb_encode.h>
#include <src/config/unit_tests.h>
#include <src/debug_interface/debug_stream.h>
#include <src/messages/SensorReading.pb.h>
#include <src/util/message_codes.h>
#include <test_runners/debug_interface_tests.h>
#include <src/util/memory_troubleshooter.h>
#include <external/etl/exception.h>

void TestRequestMessageFromSimulator(void);
void TestPostMessageToDebugClient(void);

#endif  // TEST_RUNNERS_DEBUG_INTERFACE_TESTS_H_
