/* AUTOGENERATED FILE. DO NOT EDIT. */

#ifndef TEST_RUNNERS_EARTH_SENSOR_TESTS_H_
#define TEST_RUNNERS_EARTH_SENSOR_TESTS_H_

#include "unity.h"
#include <math.h>
#include <src/sensors/earth_sensor.h>
#include <src/sensors/infrared_sensor.h>
#include <src/util/memory_troubleshooter.h>
#include <external/etl/exception.h>

void TestInfraredToAngle(void);
void TestCalculateNadirVector(void);

#endif  // TEST_RUNNERS_EARTH_SENSOR_TESTS_H_
