/* AUTOGENERATED FILE. DO NOT EDIT. */

#ifndef TEST_RUNNERS_FINITE_DIFFERENCE_SYMMETRIC_TESTS_H_
#define TEST_RUNNERS_FINITE_DIFFERENCE_SYMMETRIC_TESTS_H_

#include "unity.h"
#include <src/util/finite_difference_symmetric.h>
#include <test_runners/finite_difference_symmetric_tests.h>

void TestProcessSampleDifferentiator(void);

#endif  // TEST_RUNNERS_FINITE_DIFFERENCE_SYMMETRIC_TESTS_H_
