/* AUTOGENERATED FILE. DO NOT EDIT. */

#ifndef TEST_RUNNERS_FIRST_ORDER_IIR_LOWPASS_TESTS_H_
#define TEST_RUNNERS_FIRST_ORDER_IIR_LOWPASS_TESTS_H_

#include "unity.h"
#include <math.h>
#include <src/util/first_order_iir_lowpass.h>
#include <test_runners/first_order_iir_lowpass_tests.h>
#include <src/util/memory_troubleshooter.h>
#include <external/etl/exception.h>

void TestProcessSampleFilter(void);

#endif  // TEST_RUNNERS_FIRST_ORDER_IIR_LOWPASS_TESTS_H_
