/* AUTOGENERATED FILE. DO NOT EDIT. */

#ifndef TEST_RUNNERS_GENERIC_SENSOR_TESTS_H_
#define TEST_RUNNERS_GENERIC_SENSOR_TESTS_H_

#include "unity.h"
#include <test_runners/generic_sensor_tests.h>
#include <src/sensors/specific_sensors/test_i2c_sensor.h>
#include <src/observers/specific_observers/test_observer.h>

void TestGenericSensor(void);

#endif  // TEST_RUNNERS_GENERIC_SENSOR_TESTS_H_
