/* AUTOGENERATED FILE. DO NOT EDIT. */

#ifndef TEST_RUNNERS_I2C_SENSOR_TESTS_H_
#define TEST_RUNNERS_I2C_SENSOR_TESTS_H_

#include "unity.h"
#include <Board.h>
#include <src/config/unit_tests.h>
#include <src/i2c/i2c.h>
#include <src/i2c/multiplexers/i2c_multiplexer.h>
#include <src/observers/specific_observers/test_observer.h>
#include <src/sensors/i2c_sensors/adc.h>
#include <test_runners/i2c_sensor_tests.h>

void TestADC(void);

#endif  // TEST_RUNNERS_I2C_SENSOR_TESTS_H_
