/* AUTOGENERATED FILE. DO NOT EDIT. */

#ifndef TEST_RUNNERS_I2C_TESTS_H_
#define TEST_RUNNERS_I2C_TESTS_H_

#include "unity.h"
#include <src/board/board.h>
#include <test_runners/i2c_tests.h>
#include <src/i2c/i2c.h>
#include <src/config/unit_tests.h>
#include <ti/sysbios/knl/Task.h>
#include <src/util/memory_troubleshooter.h>
#include <external/etl/exception.h>

void TestI2cWriteTransaction(void);
void TestI2cReadTransaction(void);

#endif  // TEST_RUNNERS_I2C_TESTS_H_
