/* AUTOGENERATED FILE. DO NOT EDIT. */

#ifndef TEST_RUNNERS_INA169_TESTS_H_
#define TEST_RUNNERS_INA169_TESTS_H_

#include "unity.h"
#include <Board.h>
#include <src/config/unit_tests.h>
#include <src/i2c/i2c.h>
#include <src/i2c/multiplexers/i2c_multiplexer.h>
#include <src/sensors/i2c_sensors/current_sensors/ina169.h>
#include <src/sensors/i2c_sensors/measurables/ina169_current_measurable.h>
#include <test_runners/ina169_tests.h>
#include <src/util/memory_troubleshooter.h>
#include <external/etl/exception.h>

void TestIna169CurrentRead(void);

#endif  // TEST_RUNNERS_INA169_TESTS_H_
