/* AUTOGENERATED FILE. DO NOT EDIT. */

#ifndef TEST_RUNNERS_INA211_TESTS_H_
#define TEST_RUNNERS_INA211_TESTS_H_

#include "unity.h"
#include <Board.h>
#include <src/config/unit_tests.h>
#include <src/i2c/i2c.h>
#include <src/i2c/multiplexers/i2c_multiplexer.h>
#include <src/sensors/i2c_sensors/current_sensors/ina211.h>
#include <src/sensors/i2c_sensors/measurables/ina211_current_measurable.h>
#include <test_runners/ina211_tests.h>
#include <src/util/memory_troubleshooter.h>
#include <external/etl/exception.h>

void TestIna211CurrentRead(void);

#endif  // TEST_RUNNERS_INA211_TESTS_H_
