/* AUTOGENERATED FILE. DO NOT EDIT. */

#ifndef TEST_RUNNERS_IO_EXPANDER_TESTS_H_
#define TEST_RUNNERS_IO_EXPANDER_TESTS_H_

#include "unity.h"
#include <src/board/board.h>
#include <src/config/unit_tests.h>
#include <src/i2c/i2c.h>
#include <src/i2c/io_expander/io_expander.h>
#include <src/i2c/multiplexers/i2c_multiplexer.h>
#include <src/util/data_types.h>
#include <test_runners/io_expander_tests.h>
#include <src/util/memory_troubleshooter.h>
#include <external/etl/exception.h>

void TestIoExpander(void);

#endif  // TEST_RUNNERS_IO_EXPANDER_TESTS_H_
