/* AUTOGENERATED FILE. DO NOT EDIT. */

#ifndef TEST_RUNNERS_KALMAN_FILTER_TESTS_H_
#define TEST_RUNNERS_KALMAN_FILTER_TESTS_H_

#include "unity.h"
#include <src/adcs/kalman_filter.h>
#include <src/util/matrix.h>
#include <test_runners/matrix_tests.h>
#include <src/util/memory_troubleshooter.h>

void TestKalmanPredictAndUpdate(void);

#endif  // TEST_RUNNERS_KALMAN_FILTER_TESTS_H_
