/* AUTOGENERATED FILE. DO NOT EDIT. */

#ifndef TEST_RUNNERS_LITHIUM_HARDWARE_TESTS_H_
#define TEST_RUNNERS_LITHIUM_HARDWARE_TESTS_H_

#include "unity.h"
#include <src/config/unit_tests.h>
#include <src/telecomms/lithium.h>
#include <src/util/data_types.h>
#include <test_runners/lithium_hardware_tests.h>

void TestCommandAcks(void);

#endif  // TEST_RUNNERS_LITHIUM_HARDWARE_TESTS_H_
