/* AUTOGENERATED FILE. DO NOT EDIT. */

#ifndef TEST_RUNNERS_LITHIUM_CONFIGURATION_TESTS_H_
#define TEST_RUNNERS_LITHIUM_CONFIGURATION_TESTS_H_

#include "unity.h"
#include <src/config/unit_tests.h>
#include <src/telecomms/lithium_configuration.h>
#include <src/telecomms/lithium_function_config.h>
#include <src/telecomms/lithium_utils.h>
#include <src/util/memory_troubleshooter.h>
#include <external/etl/exception.h>

void TestLithiumConfigurationSerialise(void);
void TestLithiumConfigurationDeserialise(void);
void TestFunctionConfigDeserialise(void);

#endif  // TEST_RUNNERS_LITHIUM_CONFIGURATION_TESTS_H_
