/* AUTOGENERATED FILE. DO NOT EDIT. */

#ifndef TEST_RUNNERS_LITHIUM_COMMAND_SERIALISE_TESTS_H_
#define TEST_RUNNERS_LITHIUM_COMMAND_SERIALISE_TESTS_H_

#include "unity.h"
#include <src/telecomms/lithium.h>
#include <src/telecomms/lithium_utils.h>
#include <src/util/data_types.h>
#include <test_runners/lithium_command_serialise_tests.h>

void TestNoOpSerialisation(void);
void TestResetSystemSerialisation(void);
void TestGetConfigurationSerialisation(void);
void TestTransmitTestPayloadSerialisation(void);
void TestWriteFlashSerialisation(void);

#endif  // TEST_RUNNERS_LITHIUM_COMMAND_SERIALISE_TESTS_H_
