/* AUTOGENERATED FILE. DO NOT EDIT. */

#ifndef TEST_RUNNERS_LITHIUM_COMMAND_TESTS_H_
#define TEST_RUNNERS_LITHIUM_COMMAND_TESTS_H_

#include "unity.h"
#include <src/telecomms/lithium.h>
#include <src/telecomms/runnable_lithium.h>
#include <test_runners/lithium_command_tests.h>

void TestNoOpSerialisation(void);
void TestResetSystemSerialisation(void);
void TestGetConfigurationSerialisation(void);
void TestTransmitTestPayload(void);

#endif  // TEST_RUNNERS_LITHIUM_COMMAND_TESTS_H_
