/* AUTOGENERATED FILE. DO NOT EDIT. */

#ifndef TEST_RUNNERS_LOCATION_ESTIMATOR_TESTS_H_
#define TEST_RUNNERS_LOCATION_ESTIMATOR_TESTS_H_

#include "unity.h"
#include <src/adcs/state_estimators/location_estimator.h>
#include <test_runners/location_estimator_tests.h>
#include <src/util/memory_troubleshooter.h>
#include <external/etl/exception.h>

void TestUpdateLocation(void);

#endif  // TEST_RUNNERS_LOCATION_ESTIMATOR_TESTS_H_
