/* AUTOGENERATED FILE. DO NOT EDIT. */

#ifndef TEST_RUNNERS_MAGNETOMETER_TESTS_H_
#define TEST_RUNNERS_MAGNETOMETER_TESTS_H_

#include "unity.h"
#include <src/messages/MagnetometerReading.pb.h>
#include <src/sensors/specific_sensors/magnetometer.h>
#include <test_runners/magnetometer_tests.h>
#include <src/config/unit_tests.h>
#include <src/util/memory_troubleshooter.h>

void TestMagnetometer(void);

#endif  // TEST_RUNNERS_MAGNETOMETER_TESTS_H_
