/* AUTOGENERATED FILE. DO NOT EDIT. */

#ifndef TEST_RUNNERS_MAGNETOMETER_CALIBRATION_TESTS_H_
#define TEST_RUNNERS_MAGNETOMETER_CALIBRATION_TESTS_H_

#include "unity.h"
#include <src/sensors/magnetometer_calibration.h>
#include <test_runners/magnetometer_calibration_tests.h>
#include <src/util/memory_troubleshooter.h>
#include <external/etl/exception.h>

void TestMagnetometerCalibration(void);
void TestComputeS(void);

#endif  // TEST_RUNNERS_MAGNETOMETER_CALIBRATION_TESTS_H_
