/* AUTOGENERATED FILE. DO NOT EDIT. */

#ifndef TEST_RUNNERS_MASTER_RUNNER_H_
#define TEST_RUNNERS_MASTER_RUNNER_H_

void master_tests_thread();
void debug_interface_tests_runner();
void i2c_tests_runner();
void message_tests_runner();
void antenna_tests_runner();
void lithium_ack_tests_runner();
void lithium_command_tests_runner();
void lithium_hardware_tests_runner();
void SetUp();
void TearDown();

#endif  // TEST_RUNNERS_MASTER_RUNNER_H_
