/* AUTOGENERATED FILE. DO NOT EDIT. */

#ifndef TEST_RUNNERS_MASTER_RUNNER_H_
#define TEST_RUNNERS_MASTER_RUNNER_H_

void *master_tests_thread(void *);
void message_tests_runner();
void SetUp();
void TearDown();

#endif  // TEST_RUNNERS_MASTER_RUNNER_H_
