/* AUTOGENERATED FILE. DO NOT EDIT. */

#ifndef TEST_RUNNERS_MATRIX_TESTS_H_
#define TEST_RUNNERS_MATRIX_TESTS_H_

#include "unity.h"
#include <external/etl/exception.h>
#include <math.h>
#include <src/util/data_types.h>
#include <src/util/matrix.h>
#include <test_runners/matrix_tests.h>
#include <src/util/memory_troubleshooter.h>


#endif  // TEST_RUNNERS_MATRIX_TESTS_H_
