/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Test Runner Used To Run Each Test Below=====*/
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      SetUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT()) \
  { \
    TearDown(); \
  } \
  UnityConcludeTest(); \
}

/*=======Automagically Detected Files To Include=====*/
#ifdef __WIN32__
#define UNITY_INCLUDE_SETUP_STUBS
#endif
#include "unity.h"
#ifndef UNITY_EXCLUDE_SETJMP_H
#include <setjmp.h>
#endif
#include <stdio.h>
#include "matrix_tests.h"

/*=======External Functions This Runner Calls=====*/
extern void SetUp(void);
extern void TearDown(void);
extern void TestDotProduct();
extern void TestQuaternionConjugate();
extern void TestQuaternionDotProduct();
extern void TestQuaternionCrossProduct();
extern void TestCopyConstructor();
extern void TestSlice();
extern void TestGetNRows();
extern void TestGetNColumns();
extern void TestIsSquare();
extern void TestGet();
extern void TestSet();
extern void TestDoubleIsEqual();
extern void TestIsEqual();
extern void TestSameSize();
extern void TestSameNRows();
extern void TestSameNColumns();
extern void TestTranspose();
extern void TestVectorNorm();
extern void TestAdd();
extern void TestSubtract();
extern void TestMultiply();
extern void TestMultiplyScalar();
extern void TestCrossProduct();
extern void TestFill();
extern void TestCopyInto();
extern void TestIdentity();
extern void TestQuaternionNormalise();
extern void TestRotationMatrixFromQuaternion();
extern void TestSkewSymmetricFill();
extern void TestConcatenateHorizontally();
extern void TestConcatenateVertically();
extern void TestAddRows();
extern void TestMultiplyRow();
extern void TestSwitchRows();
extern void TestRowReduce();


/*=======Suite Setup=====*/
static MemoryTroubleshooter *suite_setup(void)
{
  MemoryTroubleshooter *mem_test = new MemoryTroubleshooter();
#if defined(UNITY_WEAK_ATTRIBUTE) || defined(UNITY_WEAK_PRAGMA)
  suiteSetUp();
#endif
  return mem_test;
}

/*=======Suite Teardown=====*/
static int suite_teardown(int num_failures, MemoryTroubleshooter *mem_test)
{
    if(mem_test->MemoryLeakTest()){
        UNITY_PRINT_EOL();
        UnityPrint(memoryLeakMessage);
        UNITY_PRINT_EOL();
    }
    mem_test->~MemoryTroubleshooter();
#if defined(UNITY_WEAK_ATTRIBUTE) || defined(UNITY_WEAK_PRAGMA)
  return suiteTearDown(num_failures);
#else
  return num_failures;
#endif
}

/*=======Test Reset Option=====*/
void resetTest_matrix_tests_runner(void);
void resetTest_matrix_tests_runner(void)
{
  TearDown();
  SetUp();
}


/*=======MAIN=====*/
 int matrix_tests_runner(void);
int matrix_tests_runner(void)
{
  MemoryTroubleshooter *mem_test = suite_setup();
  UnityBegin("src/util/tests/matrix_tests.cpp");
  RUN_TEST(TestDotProduct, 8);
  RUN_TEST(TestQuaternionConjugate, 20);
  RUN_TEST(TestQuaternionDotProduct, 30);
  RUN_TEST(TestQuaternionCrossProduct, 43);
  RUN_TEST(TestCopyConstructor, 56);
  RUN_TEST(TestSlice, 75);
  RUN_TEST(TestGetNRows, 99);
  RUN_TEST(TestGetNColumns, 106);
  RUN_TEST(TestIsSquare, 113);
  RUN_TEST(TestGet, 123);
  RUN_TEST(TestSet, 141);
  RUN_TEST(TestDoubleIsEqual, 164);
  RUN_TEST(TestIsEqual, 181);
  RUN_TEST(TestSameSize, 203);
  RUN_TEST(TestSameNRows, 215);
  RUN_TEST(TestSameNColumns, 227);
  RUN_TEST(TestTranspose, 239);
  RUN_TEST(TestVectorNorm, 260);
  RUN_TEST(TestAdd, 277);
  RUN_TEST(TestSubtract, 302);
  RUN_TEST(TestMultiply, 327);
  RUN_TEST(TestMultiplyScalar, 353);
  RUN_TEST(TestCrossProduct, 376);
  RUN_TEST(TestFill, 401);
  RUN_TEST(TestCopyInto, 412);
  RUN_TEST(TestIdentity, 448);
  RUN_TEST(TestQuaternionNormalise, 469);
  RUN_TEST(TestRotationMatrixFromQuaternion, 503);
  RUN_TEST(TestSkewSymmetricFill, 544);
  RUN_TEST(TestConcatenateHorizontally, 589);
  RUN_TEST(TestConcatenateVertically, 624);
  RUN_TEST(TestAddRows, 659);
  RUN_TEST(TestMultiplyRow, 688);
  RUN_TEST(TestSwitchRows, 708);
  RUN_TEST(TestRowReduce, 736);

  return suite_teardown(UnityEnd(), mem_test);
}
