/* AUTOGENERATED FILE. DO NOT EDIT. */

#ifndef TEST_RUNNERS_MATRIX_TESTS_H_
#define TEST_RUNNERS_MATRIX_TESTS_H_

#include "unity.h"
#include <external/etl/exception.h>
#include <math.h>
#include <src/util/data_types.h>
#include <src/util/matrix.h>
#include <test_runners/matrix_tests.h>
#include <src/util/memory_troubleshooter.h>

void TestQuaternionConjugate(void);
void TestQuaternionDotProduct(void);
void TestQuaternionCrossProduct(void);
void TestCopyConstructor(void);
void TestSlice(void);
void TestGetNRows(void);
void TestGetNColumns(void);
void TestIsSquare(void);
void TestGet(void);
void TestSet(void);
void TestDoubleIsEqual(void);
void TestIsEqual(void);
void TestSameSize(void);
void TestSameNRows(void);
void TestSameNColumns(void);
void TestTranspose(void);
void TestVectorNorm(void);
void TestAdd(void);
void TestSubtract(void);
void TestMultiply(void);
void TestMultiplyScalar(void);
void TestCrossProduct(void);
void TestFill(void);
void TestCopyInto(void);
void TestIdentity(void);
void TestQuaternionNormalise(void);
void TestRotationMatrixFromQuaternion(void);
void TestSkewSymmetricFill(void);
void TestConcatenateHorizontally(void);
void TestConcatenateVertically(void);
void TestAddRows(void);
void TestMultiplyRow(void);
void TestSwitchRows(void);
void TestRowReduce(void);

#endif  // TEST_RUNNERS_MATRIX_TESTS_H_
