/* AUTOGENERATED FILE. DO NOT EDIT. */

#ifndef TEST_RUNNERS_MATRIX_TESTS_H_
#define TEST_RUNNERS_MATRIX_TESTS_H_

#include "unity.h"
#include <src/util/data_types.h>
#include <src/util/matrix.h>
#include <test_runners/matrix_tests.h>

void TestGetNRows(void);
void TestGetNColumns(void);
void TestIsSquare(void);
void TestGet(void);
void TestSet(void);
void TestDoubleIsEqual(void);
void TestIsEqual(void);
void TestSameSize(void);
void TestSameNRows(void);
void TestSameNColumns(void);
void TestTranspose(void);
void TestAdd(void);
void TestSubtract(void);
void TestMultiply(void);
void TestMultiplyScalar(void);
void TestFill(void);
void TestIdentity(void);
void TestConcatenateHorizontally(void);
void TestConcatenateVertically(void);
void TestAddRows(void);
void TestMultiplyRow(void);
void TestSwitchRows(void);
void TestRowReduce(void);

#endif  // TEST_RUNNERS_MATRIX_TESTS_H_
