/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Test Runner Used To Run Each Test Below=====*/
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      SetUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT()) \
  { \
    TearDown(); \
  } \
  UnityConcludeTest(); \
}

/*=======Automagically Detected Files To Include=====*/
#ifdef __WIN32__
#define UNITY_INCLUDE_SETUP_STUBS
#endif
#include "unity.h"
#ifndef UNITY_EXCLUDE_SETJMP_H
#include <setjmp.h>
#endif
#include <stdio.h>
#include "matrix_tests.h"

/*=======External Functions This Runner Calls=====*/
extern void SetUp(void);
extern void TearDown(void);
extern void TestQuaternionConjugate();
extern void TestQuaternionDotProduct();
extern void TestQuaternionCrossProduct();
extern void TestCopyConstructor();
extern void TestSlice();
extern void TestGetNRows();
extern void TestGetNColumns();
extern void TestIsSquare();
extern void TestGet();
extern void TestSet();
extern void TestDoubleIsEqual();
extern void TestIsEqual();
extern void TestSameSize();
extern void TestSameNRows();
extern void TestSameNColumns();
extern void TestTranspose();
extern void TestVectorNorm();
extern void TestAdd();
extern void TestSubtract();
extern void TestMultiply();
extern void TestMultiplyScalar();
extern void TestCrossProduct();
extern void TestFill();
extern void TestCopyInto();
extern void TestIdentity();
extern void TestQuaternionNormalise();
extern void TestRotationMatrixFromQuaternion();
extern void TestSkewSymmetricFill();
extern void TestConcatenateHorizontally();
extern void TestConcatenateVertically();
extern void TestAddRows();
extern void TestMultiplyRow();
extern void TestSwitchRows();
extern void TestRowReduce();


/*=======Suite Setup=====*/
static MemoryTroubleshooter *suite_setup(void)
{
  MemoryTroubleshooter *mem_test = new MemoryTroubleshooter();
#if defined(UNITY_WEAK_ATTRIBUTE) || defined(UNITY_WEAK_PRAGMA)
  suiteSetUp();
#endif
  return mem_test;
}

/*=======Suite Teardown=====*/
static int suite_teardown(int num_failures, MemoryTroubleshooter *mem_test)
{
    if(mem_test->MemoryLeakTest()){
        UNITY_PRINT_EOL();
        UnityPrint(memoryLeakMessage);
        UNITY_PRINT_EOL();
    }
    mem_test->~MemoryTroubleshooter();
#if defined(UNITY_WEAK_ATTRIBUTE) || defined(UNITY_WEAK_PRAGMA)
  return suiteTearDown(num_failures);
#else
  return num_failures;
#endif
}

/*=======Test Reset Option=====*/
void resetTest_matrix_tests_runner(void);
void resetTest_matrix_tests_runner(void)
{
  TearDown();
  SetUp();
}


/*=======MAIN=====*/
 int matrix_tests_runner(void);
int matrix_tests_runner(void)
{
  MemoryTroubleshooter *mem_test = suite_setup();
  UnityBegin("src/util/tests/matrix_tests.cpp");
  RUN_TEST(TestQuaternionConjugate, 8);
  RUN_TEST(TestQuaternionDotProduct, 19);
  RUN_TEST(TestQuaternionCrossProduct, 32);
  RUN_TEST(TestCopyConstructor, 45);
  RUN_TEST(TestSlice, 64);
  RUN_TEST(TestGetNRows, 88);
  RUN_TEST(TestGetNColumns, 95);
  RUN_TEST(TestIsSquare, 102);
  RUN_TEST(TestGet, 112);
  RUN_TEST(TestSet, 130);
  RUN_TEST(TestDoubleIsEqual, 153);
  RUN_TEST(TestIsEqual, 170);
  RUN_TEST(TestSameSize, 192);
  RUN_TEST(TestSameNRows, 204);
  RUN_TEST(TestSameNColumns, 216);
  RUN_TEST(TestTranspose, 228);
  RUN_TEST(TestVectorNorm, 249);
  RUN_TEST(TestAdd, 266);
  RUN_TEST(TestSubtract, 291);
  RUN_TEST(TestMultiply, 316);
  RUN_TEST(TestMultiplyScalar, 342);
  RUN_TEST(TestCrossProduct, 365);
  RUN_TEST(TestFill, 390);
  RUN_TEST(TestCopyInto, 401);
  RUN_TEST(TestIdentity, 437);
  RUN_TEST(TestQuaternionNormalise, 458);
  RUN_TEST(TestRotationMatrixFromQuaternion, 492);
  RUN_TEST(TestSkewSymmetricFill, 533);
  RUN_TEST(TestConcatenateHorizontally, 578);
  RUN_TEST(TestConcatenateVertically, 613);
  RUN_TEST(TestAddRows, 648);
  RUN_TEST(TestMultiplyRow, 677);
  RUN_TEST(TestSwitchRows, 697);
  RUN_TEST(TestRowReduce, 725);

  return suite_teardown(UnityEnd(), mem_test);
}
