/* AUTOGENERATED FILE. DO NOT EDIT. */

#ifndef TEST_RUNNERS_MEASURABLE_MANAGER_TESTS_H_
#define TEST_RUNNERS_MEASURABLE_MANAGER_TESTS_H_

#include "unity.h"
#include <src/sensors/i2c_measurable_manager.h>
#include <src/sensors/measurable_id.h>
#include <test_runners/measurable_manager_tests.h>
#include <src/util/memory_troubleshooter.h>

void TestManagerRead(void);

#endif  // TEST_RUNNERS_MEASURABLE_MANAGER_TESTS_H_
