/* AUTOGENERATED FILE. DO NOT EDIT. */

#ifndef TEST_RUNNERS_MEMORY_TROUBLESHOOTER_TESTS_H_
#define TEST_RUNNERS_MEMORY_TROUBLESHOOTER_TESTS_H_

#include "unity.h"
#include <src/config/unit_tests.h>
#include <src/util/memory_troubleshooter.h>
#include <test_runners/memory_troubleshooter_tests.h>
#include <src/util/memory_troubleshooter.h>

void TestMemoryLeak(void);

#endif  // TEST_RUNNERS_MEMORY_TROUBLESHOOTER_TESTS_H_
