/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MESSAGE_TESTS_H
#define _MESSAGE_TESTS_H

#include "unity.h"
#include <src/messages/serialised_message.h>
#include <src/messages/test_message.h>
#include <test_runners/message_tests.h>

void TestSerialiseMessage(void);
#endif

