/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Test Runner Used To Run Each Test Below=====*/
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      SetUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT()) \
  { \
    TearDown(); \
  } \
  UnityConcludeTest(); \
}

/*=======Automagically Detected Files To Include=====*/
#ifdef __WIN32__
#define UNITY_INCLUDE_SETUP_STUBS
#endif
#include "unity.h"
#ifndef UNITY_EXCLUDE_SETJMP_H
#include <setjmp.h>
#endif
#include <stdio.h>
#include "mpu9250_motion_tracker_tests.h"

/*=======External Functions This Runner Calls=====*/
extern void SetUp(void);
extern void TearDown(void);
extern void TestGyroRead(void);
extern void TestMagnoRead(void);
extern void TestTempRead(void);
extern void TestAccelRead(void);


/*=======Suite Setup=====*/
static MemoryTroubleshooter *suite_setup(void)
{
  MemoryTroubleshooter *mem_test = new MemoryTroubleshooter();
#if defined(UNITY_WEAK_ATTRIBUTE) || defined(UNITY_WEAK_PRAGMA)
  suiteSetUp();
#endif
  return mem_test;
}

/*=======Suite Teardown=====*/
static int suite_teardown(int num_failures, MemoryTroubleshooter *mem_test)
{
    if(mem_test->MemoryLeakTest()){
        UNITY_PRINT_EOL();
        UnityPrint(memoryLeakMessage);
        UNITY_PRINT_EOL();
    }
    mem_test->~MemoryTroubleshooter();
#if defined(UNITY_WEAK_ATTRIBUTE) || defined(UNITY_WEAK_PRAGMA)
  return suiteTearDown(num_failures);
#else
  return num_failures;
#endif
}

/*=======Test Reset Option=====*/
void resetTest_mpu9250_motion_tracker_tests_runner(void);
void resetTest_mpu9250_motion_tracker_tests_runner(void)
{
  TearDown();
  SetUp();
}


/*=======MAIN=====*/
 int mpu9250_motion_tracker_tests_runner(void);
int mpu9250_motion_tracker_tests_runner(void)
{
  MemoryTroubleshooter *mem_test = suite_setup();
  UnityBegin("src/sensors/i2c_sensors/tests/mpu9250_motion_tracker_tests.cpp");
  RUN_TEST(TestGyroRead, 16);
  RUN_TEST(TestMagnoRead, 32);
  RUN_TEST(TestTempRead, 49);
  RUN_TEST(TestAccelRead, 65);

  return suite_teardown(UnityEnd(), mem_test);
}
