/* AUTOGENERATED FILE. DO NOT EDIT. */

#ifndef TEST_RUNNERS_MULTIPLEXER_TESTS_H_
#define TEST_RUNNERS_MULTIPLEXER_TESTS_H_

#include "unity.h"
#include <src/board/board.h>
#include <src/config/unit_tests.h>
#include <src/i2c/i2c.h>
#include <src/i2c/multiplexers/i2c_multiplexer.h>
#include <src/sensors/i2c_sensors/measurables/temperature_measurable.h>
#include <src/util/data_types.h>
#include <test_runners/i2c_tests.h>
#include <src/sensors/i2c_sensors/mcp9808.hpp>
#include <src/util/memory_troubleshooter.h>
#include <external/etl/exception.h>

void TestMultiplexer(void);

#endif  // TEST_RUNNERS_MULTIPLEXER_TESTS_H_
