/* AUTOGENERATED FILE. DO NOT EDIT. */

#ifndef TEST_RUNNERS_NADIR_ERROR_GENERATOR_TESTS_H_
#define TEST_RUNNERS_NADIR_ERROR_GENERATOR_TESTS_H_

#include "unity.h"
#include <src/util/memory_troubleshooter.h>
#include <external/etl/exception.h>


#endif  // TEST_RUNNERS_NADIR_ERROR_GENERATOR_TESTS_H_
