/* AUTOGENERATED FILE. DO NOT EDIT. */

#ifndef TEST_RUNNERS_PAYLOAD_PROCESSOR_TESTS_H_
#define TEST_RUNNERS_PAYLOAD_PROCESSOR_TESTS_H_

#include "unity.h"
#include <external/nanopb/pb_encode.h>
#include <src/messages/Tle.pb.h>
#include <src/payload_processor/commands/test_command.h>
#include <src/payload_processor/commands/tle_update_command.h>
#include <src/payload_processor/payload_processor.h>
#include <src/telecomms/lithium.h>
#include <test_runners/payload_processor_tests.h>
#include <ti/sysbios/BIOS.h>
#include <ti/sysbios/knl/Mailbox.h>
#include <src/util/memory_troubleshooter.h>
#include <external/etl/exception.h>

void TestPayloadProcessor(void);
void TestTleUpdateCommand(void);

#endif  // TEST_RUNNERS_PAYLOAD_PROCESSOR_TESTS_H_
