/* AUTOGENERATED FILE. DO NOT EDIT. */

#ifndef TEST_RUNNERS_PAYLOAD_PROCESSOR_TESTS_H_
#define TEST_RUNNERS_PAYLOAD_PROCESSOR_TESTS_H_

#include "unity.h"
#include <src/payload_processor/payload_processor.h>
#include <src/telecomms/lithium.h>
#include <test_runners/payload_processor_tests.h>
#include <src/payload_processor/commands/test_command.h>

void TestPayloadProcessor(void);

#endif  // TEST_RUNNERS_PAYLOAD_PROCESSOR_TESTS_H_
