/* AUTOGENERATED FILE. DO NOT EDIT. */

#ifndef TEST_RUNNERS_RTC_TESTS_H_
#define TEST_RUNNERS_RTC_TESTS_H_

#include "unity.h"
#include <Board.h>
#include <src/config/unit_tests.h>
#include <src/sensors/i2c_sensors/rtc.h>
#include <test_runners/rtc_tests.h>
#include <time.h>

void TestRtcReadTransaction(void);

#endif  // TEST_RUNNERS_RTC_TESTS_H_
