/* AUTOGENERATED FILE. DO NOT EDIT. */

#ifndef TEST_RUNNERS_RTC_TESTS_H_
#define TEST_RUNNERS_RTC_TESTS_H_

#include "unity.h"
#include <src/board/board.h>
#include <src/config/unit_tests.h>
#include <src/i2c/multiplexers/i2c_multiplexer.h>
#include <src/sensors/i2c_sensors/rtc.h>
#include <test_runners/rtc_tests.h>
#include <time.h>
#include <src/util/memory_troubleshooter.h>
#include <external/etl/exception.h>

void TestRtcReadTransaction(void);

#endif  // TEST_RUNNERS_RTC_TESTS_H_
