/* AUTOGENERATED FILE. DO NOT EDIT. */

#ifndef TEST_RUNNERS_SGP4_TESTS_H_
#define TEST_RUNNERS_SGP4_TESTS_H_

#include "unity.h"
#include <external/sgp4/sgp4.h>
#include <external/sgp4/sgp4_utils.h>
#include <math.h>
#include <test_runners/sgp4_tests.h>
#include <src/util/memory_troubleshooter.h>

void TestSimplifiedGeneralPerturbationModel(void);

#endif  // TEST_RUNNERS_SGP4_TESTS_H_
