/* AUTOGENERATED FILE. DO NOT EDIT. */

#ifndef TEST_RUNNERS_SPI_TESTS_H_
#define TEST_RUNNERS_SPI_TESTS_H_

#include "unity.h"
#include <Board.h>
#include <src/config/unit_tests.h>
#include <src/spi/spi.h>
#include <test_runners/spi_tests.h>
#include <ti/sysbios/knl/Task.h>

void TestSpiWriteTransaction(void);
void TestSpiReadTransaction(void);

#endif  // TEST_RUNNERS_SPI_TESTS_H_
