/* AUTOGENERATED FILE. DO NOT EDIT. */

#ifndef TEST_RUNNERS_WMM_TESTS_H_
#define TEST_RUNNERS_WMM_TESTS_H_

#include "unity.h"
#include <external/wmm/worldMagneticModel.h>
#include <test_runners/wmm_tests.h>
#include <src/util/memory_troubleshooter.h>
#include <external/etl/exception.h>

void TestWorldMagneticModel(void);

#endif  // TEST_RUNNERS_WMM_TESTS_H_
