#ifndef SRC_BOARD_BOARD_H_
#define SRC_BOARD_BOARD_H_

#include "MSP432E.h"

#define Board_TIMER2 MSP_EXP432P401R_TIMER_TA_1
#define Board_TIMER3 MSP_EXP432P401R_TIMER_TA_2

#endif  // SRC_BOARD_BOARD_H_
